### ISSUE TITLE
Crash when Arrow Entity loaded

### ISSUE THREAD

**Issue by Aaron2550** [Pokechu22/WorldDownloader#101]
My game crashes everytime the game loads in an Arrow, doesnt matter if its stuck in a wall or fired by a skeleton.

Crashlog:
https://pastebin.com/nXuTYzAu

**Comment by Pokechu22** [comment]
See #97.  This is a known issue with 1.13.1, and it'll be fixed in the next version when I release an _actual_ 1.13.1 build instead of the current 1.13.1 from 1.13 thing.  But in the mean time, it is still an issue.

**Comment by Aaron2550** [comment]
Sorry for not checking if its already been posted, any ETA until the 1.13.1 release? And thanks for the quick answer!

**Comment by Pokechu22** [comment]
It should be soon, but it'll probably be after 1.13.2 comes out (which is planned for Thursday).  I'm trying to get all of the build system stuff fixed by then in addition to this and several other issues.

**Comment by Aaron2550** [comment]
1.13.2 is planned for thursday huh... The server im playing on resets on every new version, that means i need to get the world until thursday. Damnit, server reset on my birthday... well thx for the ETA

**Comment by Pokechu22** [comment]
1.13.2 was pushed back to next monday (which I'm sure you've already heard about).  I'm not sure if I can get everything done by then, but I'll try to get a 1.13.1 build out before then if possible.  Happy birthday!

**Comment by Aaron2550** [comment]
Next Monday? So the 22nd? Thanks for trying, and thanksfor the happy bday!

**Comment by Pokechu22** [comment]
[4.0.3.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.3.2) has been released, hopefully in time for what you need.  Note that [github is currently being somewhat unstable](https://status.github.com/messages) so you might need to wait to use that link.
