### ISSUE TITLE
FTB Ultimate?

### ISSUE THREAD

**Issue by Puyodead1** [Pokechu22/WorldDownloader#103]
Can i use this with ftb ultimate 1.4.7? if so, how?

**Comment by Pokechu22** [comment]
Minecraft 1.4.7... yikes.  I'm not sure.  The mod is old enough to have released for 1.4.6 (but not 1.4.7), but given how old that is, I have no idea how to use it (and it was far before I was the maintainer, so I don't know how to work with the code back then).  [Here's the 1.4.6 zip](https://github.com/Pokechu22/WorldDownloader/blob/b3a4ac6aae789010c7f4b0e3dadf2f750c668bf9/bin/World%20Downloader%20%5B1.4.6%5D.zip), though.

**Comment by Puyodead1** [comment]
:/ ok, thanks, i will try it
