### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by NPCtom** [Pokechu22/WorldDownloader#104]
Downloaded a part of a region on the server us.shotbow.net and when I exit the server and start the world on singleplayer it crashes immediately with the attached report.

When I start the world the second time it starts normally with no issues.

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 11/2/18 7:17 AM
Description: WDL mod: exception in onNHPCHandleCustomPayload event

[crash-2018-11-02_07.17.20-client.txt](https://github.com/Pokechu22/WorldDownloader/files/2545603/crash-2018-11-02_07.17.20-client.txt)

**Comment by Pokechu22** [comment]
Thanks for your report.  I have a vague idea as to what I did wrong here, and I should be able to fix this for the next release (which, if all goes well, will be tomorrow).  It starting normally the second time seems like odd behavior, though... based on what I'm seeing, it seems more likely that it'll be random (as a race condition).

**Comment by Pokechu22** [comment]
This should be fixed now; let me know if you're still having issues.
