### ISSUE TITLE
SUGGESTION Add Overtime Download

### ISSUE THREAD

**Issue by NPCtom** [Pokechu22/WorldDownloader#107]
Could you add a feature if you wanted to download a really big map and you had to walk around to download it could you make it you can add to the download. For example if I wanted to download a really big map I would click start download then once I am done with downloading a small portion of the map the next day I can resume downloading to the same save to continue downloading the whole map?

**Comment by Pokechu22** [comment]
This is already supported and has been supported for quite some time, including importing old contents of containers such as chests.  As long as you save with the same name as before, it'll add to the previous world.

Given that you're not the first person to ask for this, though, I think I probably need to make it more obvious that it already is supported (but I'm not 100% sure what that'd require).

**Comment by NPCtom** [comment]
OK thanks but how do I do that?

**Comment by Pokechu22** [comment]
Connect to the server you connected to before (make sure that you didn't rename anything).  If you're using multiworld, select the same world you used before (if not using multiworld, you don't need to do anything special).  Then, just download, and it should automatically happen.

**Comment by NPCtom** [comment]
It say's do you want to backup the file

**Comment by Pokechu22** [comment]
All of the options are there so you can have a backup of the world before anything you download into it (in case you download the same area twice and built something on the downloaded copy beforehand).  Areas you've already visited but don't visit again will be left as-is.  (On that screen, select either backup as zip or just skip backup; it doesn't matter too much)

**Comment by NPCtom** [comment]
OK Thanks :) Issue resolved.

**Comment by Pokechu22** [comment]
No problem.  I'll look into making things clearer in the future, but it's a rather long term goal.
