### ISSUE TITLE
How to continue downloading map after computer reset

### ISSUE THREAD

**Issue by NPCtom** [Pokechu22/WorldDownloader#113]
I was downloading a server map but erased my hard drive to clean my computer. I saved the world save onto a USB and placed it in the saves folder of my new hard drive. Before I erased the computer Multiworld support was enabled and the name was set as 'MineZ' unfortunately when I selected download world it starts downloading a new world and not continuing on the other. I have tried enabling Multiworld and adding the name MineZ but still creates a new world.

**Comment by Pokechu22** [comment]
The name needs to match exactly for it to merge.  In multiworld mode, this _also_ means the server name needs to match (the name in your server list, or the IP if using direct connect).  If you previously used the server list and are now using direct connect or vice versa, it'll save into a different name as you're experiencing.

One easy solution: once you've found what the new world that it's creating is named, copy the world you want to merge to have that name.
