### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by Slimerblue22** [Pokechu22/WorldDownloader#114]
Just wondering if there is a change log for the different versions
(bug fixes and things like that)

**Comment by Seferan** [comment]
https://github.com/Pokechu22/WorldDownloader/releases/

**Comment by Pokechu22** [comment]
Each release has a list of changes in it (and in the mod itself, the updates page also lists the same set of changes based on github releases).  I don't have any other changelog page beyond that.

**Comment by Slimerblue22** [comment]
Thank you!
