### ISSUE TITLE
Instructions to compile 1.13.x needed now that Forge 1.13.2 released

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#116]
Could you update compile instructions for 1.13.x versions now that gradle 3 and forge 1.13.2 are out ?
Thank you

**Comment by Pokechu22** [comment]
Yep, I'd like to get it ready.  Right now I'm still personally using a messy combination of FG 2 things and FG 3 data, which is why I haven't had any instructions for it yet (there's a large manual step for converting the data).  I'll need to finish updating the build scripts to forgegradle 3 (which I've been working on) and then it should be possible.

**Comment by Mustached-Man** [comment]
Can't wait for a mc1.13.2.litemod version.

**Comment by uyjulian** [comment]
Liteloader is not available for 1.13.2.

**Comment by Mustached-Man** [comment]
Darn, wish i could somehow play it on 1.13.2

**Comment by uyjulian** [comment]
You can use it on 1.13.2 using the base edit version.

**Comment by Mustached-Man** [comment]
As the zip file it's self? Or in a jar/different file format?
I've tried using it as the zip but didn't work.

**Comment by Tsoccerguy3** [comment]
Use MultiMC and create a 1.13.2 instance then add the WDL 1.13.2 to that instance

**Comment by spiny123** [comment]
> Use MultiMC and create a 1.13.2 instance then add the WDL 1.13.2 to that instance

How do you add the WDL 1.13.2 to that instance?

**Comment by spiny123** [comment]
i put world downloader mod in the "Loader Mods" 1.13.2 instance but no signs of the mod in game.

**Comment by Pokechu22** [comment]
Use "add to minecraft.jar".

**Comment by spiny123** [comment]
ty! <3

**Comment by Pokechu22** [comment]
OK, so an update to this: Assuming all goes well, I'll have a 1.14 release later today.  You should be able to build for 1.14 yourself.  1.13 is still borked, though, because I still haven't managed to fix the remapping-related issues with it (1.14 didn't run into that problem because the number of mapping differences is severe enough that I simply copied the code).  I'll still try to get 1.13 fixed when I can, because the current setup really is a pain.

To build 1.14, you _will_ currently need to manually patch the base code.  I've put the patches themselves in the same place as normal (1.14.x/src/main/base-patches), but begradle does not patch them automatically because I've had issues with it getting the source jar.  You can generate one with `gradlew eclipse` or so (it'll be generated in `<user>/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraft/client/1.14.2_mapped_snapshot_20190518-1.13.2/1.14.2_mapped_snapshot_20190518-1.13.2-sources.jar` or similar), _but_ once you do make one, attempting to build causes internal compile errors and you'll need to delete the whole `minecraft_user_repo` folder before building (which seems crazy, but it's the process I've needed to use).  Once you've patched code, you'll need to put it in `src/main/java` instead of the normal `src/main/base`, at least at the moment.  All of this will be simplified later, hopefully.

Sorry that 1.13's been in a broken state for so long (and that it _still_ is).

**Comment by Tsoccerguy3** [comment]
POKE , I had a idea, if you cant still figure out how to get this to compile ,create a batch file to setup the parts that you fix manually . or it can be a windows command script and on Linux a Bash script

**Comment by Pokechu22** [comment]
I'm not sure whether a batch file would be sufficient, because among other things I remember needing to add some files into a zip folder, and also to rename and edit part of all of the files already in the folder.  Getting things to use forgegradle 3 really is the better path.

I actually did make some progress on this on commit 0affc519f9cc8103e52dc1959d974e5a9a106409, but I don't have method/class remapping set up so the extra renames I use don't work.  This means that using that commit directly will set everything up successfully, but there will be other compile errors due to methods and the horse class not existing.  I've undone that commit since I don't have time to implement remapping yet, but once I do implement it FG3 should be fully usable and the only version that behaves weirdly will be 1.14.0 (for different reasons), with all the 1.13 versions and all the other 1.14 versions working properly.

If you want to try building from 0affc519f9cc8103e52dc1959d974e5a9a106409, go ahead; I think there's a chance it will work. Some of the mapping issues may be fixed if `mappings channel: 'snapshot', version: '20190630-1.14.3'` is changed to `mappings channel: 'snapshot', version: '20190530-1.13.2'` (one month older, targeting 1.13), though I'm not sure of that.  The intended extra mappings are found in `srgs/gamerule_methods_pre_1.14.3.csv`, `srgs/pre_1.14_methods.csv`, and `srgs/pre_1.14_fields.csv`.

**Comment by Tsoccerguy3** [comment]
Ok , i managed to get it to build everything up to 1.12.2 . I am not going to bother with 1.13.2 and 1.14.3 . I have our 1.13.2 server working , but this is not the norm . One of the important plugins , FAWE is not finished and a creative server really needs this . So I see most servers still on 1.12.2 and plugin developement has moved on to 1.14.4 . I hope that by the time 1.14.4 final is out that I have the plugins needed to convert the server . 

I tried to build 1.3.x and 1.14.x , but all i managed to create was goo . LOL . Funny ! i know . i'll try again when 1.14.4 drops . Thanks

**Comment by Tsoccerguy3** [comment]
Hi Poke , I compiled latest commit today , all packages build from command line up to and including 1.14.1 before i get errors and crashes . So it can not procede to compile 1.14.2 and 1.14.3 and 1.14.4 .

I think only 1.14.4 matters , the other subversions are not supported and 1.14.4 is the final branch until 1.15

**Comment by Pokechu22** [comment]
What errors did you get with 1.14.1?

It's worth noting that you can try to compile only a single version with `1.14.4:setupDecompWorkspace` or `1.14.4:build`.

**Comment by Tsoccerguy3** [comment]
No errors with compiling 1.14.1 , but it did crash trying to compile the rest

C:\Users\ASUS\Dev\wdl>gradlew 1.14.4:build

> Configure project :1.09.0-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.09.4-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.0-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.2-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.0-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.2-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.0-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.1-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.2-litemod
This mapping 'snapshot_20190726' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.14.1
New Dep: net.minecraft:client:1.14.1_mapped_snapshot_20190726-1.14.3

> Configure project :1.14.2
New Dep: net.minecraft:client:1.14.2_mapped_snapshot_20190726-1.14.3

> Configure project :1.14.3
New Dep: net.minecraft:client:1.14.3_mapped_snapshot_20190726-1.14.3

> Configure project :1.14.4
New Dep: net.minecraft:client:1.14.4_mapped_snapshot_20190726-1.14.3

> Task :1.14.4:test

wdl.config.settings.EntitySettingsTest > testTrackDistanceMode FAILED
    java.lang.AssertionError at EntitySettingsTest.java:36

wdl.config.settings.GeneratorSettingsTest > testGenerateStructures FAILED
    java.lang.AssertionError at GeneratorSettingsTest.java:32

wdl.config.settings.GeneratorSettingsTest > testGenerator FAILED
    java.lang.AssertionError at GeneratorSettingsTest.java:37

wdl.config.settings.MessageSettingsTest > testEnableAll FAILED
    java.lang.AssertionError at MessageSettingsTest.java:27

wdl.config.settings.PlayerSettingsTest > testHealth FAILED
    java.lang.AssertionError at PlayerSettingsTest.java:27

wdl.config.settings.PlayerSettingsTest > testHunger FAILED
    java.lang.AssertionError at PlayerSettingsTest.java:33

wdl.config.settings.PlayerSettingsTest > testPosition FAILED
    java.lang.AssertionError at PlayerSettingsTest.java:39

wdl.config.settings.WorldSettingsTest > testSpawn FAILED
    java.lang.AssertionError at WorldSettingsTest.java:57

wdl.config.settings.WorldSettingsTest > testTime FAILED
    java.lang.AssertionError at WorldSettingsTest.java:45

wdl.config.settings.WorldSettingsTest > testGameMode FAILED
    java.lang.AssertionError at WorldSettingsTest.java:39

wdl.config.settings.WorldSettingsTest > testAllowCheats FAILED
    java.lang.AssertionError at WorldSettingsTest.java:34

wdl.config.settings.WorldSettingsTest > testWeather FAILED
    java.lang.AssertionError at WorldSettingsTest.java:51

wdl.handler.block.BarrelTest > testBarrel FAILED
    java.lang.ExceptionInInitializerError at BarrelTest.java:40
        Caused by: java.lang.RuntimeException at BarrelTest.java:40
            Caused by: java.lang.UnsatisfiedLinkError at BarrelTest.java:40

wdl.handler.block.BeaconTest > testEffectlessBeacon FAILED
    java.lang.NoClassDefFoundError at BeaconTest.java:50

wdl.handler.block.BeaconTest > testOneEffectBeacon FAILED
    java.lang.NoClassDefFoundError at BeaconTest.java:64

wdl.handler.block.BeaconTest > testTwoEffectBeacon FAILED
    java.lang.NoClassDefFoundError at BeaconTest.java:80

wdl.handler.block.BlastFurnaceTest > testBlastFurance FAILED
    java.lang.NoClassDefFoundError at BlastFurnaceTest.java:41

wdl.handler.block.BlastFurnaceTest > testFields FAILED
    java.lang.NoClassDefFoundError at BlastFurnaceTest.java:55

wdl.handler.block.BrewingStandTest > testInventory FAILED
    java.lang.NoClassDefFoundError at BrewingStandTest.java:43

wdl.handler.block.BrewingStandTest > testFields FAILED
    java.lang.NoClassDefFoundError at BrewingStandTest.java:62

wdl.handler.block.ChestTest > testSimpleDoubleChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.ChestTest > testRegularAndOtherChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.ChestTest > testMultipleDoubleChests FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.ChestTest > testSingleChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.DispenserTest > testDispenser FAILED
    java.lang.NoClassDefFoundError at DispenserTest.java:37

wdl.handler.block.DropperTest > testDropper FAILED
    java.lang.NoClassDefFoundError at DropperTest.java:38

wdl.handler.block.FurnaceTest > testFurance FAILED
    java.lang.NoClassDefFoundError at FurnaceTest.java:41

wdl.handler.block.FurnaceTest > testFields FAILED
    java.lang.NoClassDefFoundError at FurnaceTest.java:55

wdl.handler.block.HopperTest > testHopper FAILED
    java.lang.NoClassDefFoundError at HopperTest.java:38

wdl.handler.block.LecternTest > testLectern FAILED
    java.lang.NoClassDefFoundError at LecternTest.java:44

wdl.handler.block.LecternTest > testPageNumber FAILED
    java.lang.NoClassDefFoundError at LecternTest.java:60

wdl.handler.block.ShulkerBoxTest > testShulkerBox FAILED
    java.lang.NoClassDefFoundError at ShulkerBoxTest.java:38

wdl.handler.block.SmokerTest > testFurance FAILED
    java.lang.NoClassDefFoundError at SmokerTest.java:41

wdl.handler.block.SmokerTest > testFields FAILED
    java.lang.NoClassDefFoundError at SmokerTest.java:55

wdl.handler.block.TrappedChestTest$TestImpl > testSimpleDoubleChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.TrappedChestTest$TestImpl > testRegularAndOtherChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.TrappedChestTest$TestImpl > testMultipleDoubleChests FAILED
    java.lang.NoClassDefFoundError

wdl.handler.block.TrappedChestTest$TestImpl > testSingleChest FAILED
    java.lang.NoClassDefFoundError

wdl.handler.entity.HopperMinecartTest > testStorageHopper FAILED
    java.lang.NoClassDefFoundError at HopperMinecartTest.java:34

wdl.handler.entity.HorseTest > testHorse[minecraft:horse (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:donkey (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:donkey (chested=true)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:mule (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:mule (chested=true)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:zombie_horse (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:skeleton_horse (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:llama (chested=false)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.HorseTest > testHorse[minecraft:llama (chested=true)] FAILED
    java.lang.NoClassDefFoundError at HorseTest.java:166

wdl.handler.entity.StorageMinecartTest > testStorageMinecart FAILED
    java.lang.NoClassDefFoundError at StorageMinecartTest.java:34

wdl.handler.entity.VillagerTest > testActiveTrade FAILED
    java.lang.NoClassDefFoundError at VillagerTest.java:47

wdl.SanityCheckTest > testMixinGuiIngameMenu FAILED
    java.lang.Exception at SanityCheckTest.java:53

wdl.SanityCheckTest > testMixinWorldClient FAILED
    java.lang.Exception at SanityCheckTest.java:59

wdl.SanityCheckTest > testMixinCrashReport FAILED
    java.lang.Exception at SanityCheckTest.java:71

wdl.SanityCheckTest > testMixinNHPC FAILED
    java.lang.Exception at SanityCheckTest.java:65

wdl.SanityCheckTest > testTranslation FAILED
    java.lang.Exception at SanityCheckTest.java:41

wdl.WDLHooksTest > testHandleChunkUnload FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:63

wdl.WDLHooksTest > testHandleCustomPayload FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:96

wdl.WDLHooksTest > testHandleBlockAction FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:85

wdl.WDLHooksTest > testDisconnect FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:74

wdl.WDLHooksTest > testWorldClientTick FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:43

wdl.WDLHooksTest > testHandleChat FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:107

wdl.WDLHooksTest > testHandleMaps FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:118

wdl.WDLHooksTest > testWorldClientRemoveEntityFromWorld FAILED
    java.lang.NoClassDefFoundError at WDLHooksTest.java:53

wdl.WDLMessageTypesTest > testCategoryTranslationStrings FAILED
    java.lang.AssertionError at WDLMessageTypesTest.java:57

wdl.WDLMessageTypesTest > testTypeTranslationStrings FAILED
    java.lang.AssertionError at WDLMessageTypesTest.java:43

358 tests completed, 65 failed, 37 skipped

> Task :1.14.4:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.14.4:test'.
> There were failing tests. See the report at: file:///C:/Users/ASUS/Dev/wdl/1.14.4/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 14s
10 actionable tasks: 4 executed, 6 up-to-date

**Comment by Pokechu22** [comment]
Hm.  I can confirm that if I run `gradlew 1.14.4:test` to just run the test code.  I'm not sure how I didn't run into that myself before... You should be able to ignore it if you add `-x test` to the command line, which tells it to skip the `test` task (which is what is currently failing)... but the tests shouldn't be failing.

Taking a look at the failure for `BarrelTest`, which has a longer message:

```
java.lang.ExceptionInInitializerError
	at net.minecraft.client.GameSettings.<init>(GameSettings.java:136)
	at wdl.versioned.TypeFunctions.createNewGameSettings(Types_1_14.java:48)
	at wdl.versioned.VersionedFunctions.createNewGameSettings(VersionedFunctions.java:504)
	at wdl.handler.AbstractWorldBehaviorTest.makeMockWorld(AbstractWorldBehaviorTest.java:114)
	at wdl.handler.block.AbstractBlockHandlerTest.makeMockWorld(AbstractBlockHandlerTest.java:89)
	at wdl.handler.block.BarrelTest.testBarrel(BarrelTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
-snip-
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at net.minecraft.client.util.InputMappings.<clinit>(InputMappings.java:103)
	... 55 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:317)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:314)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:338)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:328)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:360)
	at net.minecraft.client.util.InputMappings.<clinit>(InputMappings.java:99)
	... 55 more
```

[`UnsatisfiedLinkError`](https://docs.oracle.com/javase/8/docs/api/java/lang/UnsatisfiedLinkError.html) is "Thrown if the Java Virtual Machine cannot find an appropriate native-language definition of a method declared `native`."  LWJGL is a native library, and the message pretty clearly indicates that it failed to find it ("Failed to locate library: lwjgl.dll").  I'm not sure _why_ it would fail to find it, though...

As for why 1.14.1 isn't affected: It looks like Minecraft's `InputMappings` only started depending on native LWJGL code in 1.14.2 for raw input.  So 1.14.1 just doesn't need to look for it in that part of the code, and I don't think the unit tests hit anything else that would need it.

**Comment by Tsoccerguy3** [comment]
Tried again to build 1.14.4

D:\dev\wdl>gradlew :1.14.4:build:-x test

> Configure project :1.09.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.09.4-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.1-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.14.1
New Dep: net.minecraft:client:1.14.1_mapped_snapshot_20190708-1.14.3

> Configure project :1.14.2
New Dep: net.minecraft:client:1.14.2_mapped_snapshot_20190708-1.14.3

> Configure project :1.14.3
New Dep: net.minecraft:client:1.14.3_mapped_snapshot_20190708-1.14.3

FAILURE: Build failed with an exception.

* What went wrong:
Project '1.14.4' not found in root project 'wdl'. Some candidates are: '1.09.0', '1.09.2', '1.09.4', '1.10.0', '1.10.2', '1.11.0', '1.11.2', '1.12.0', '1.12.1', '1.12.2', '1.14.1', '1.14.2', '1.14.3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by Pokechu22** [comment]
You wrote `gradlew :1.14.4:build:-x test`, but it should have been `gradlew :1.14.4:build -x test`.  I'm not sure what the other format does... but maybe it disables the entire 1.14.4 subproject which would explain that output.

**Comment by Tsoccerguy3** [comment]
I tried it again in that format and with the setupdecompworkspace no sucess something related to 1.14.4 no doubt


C:\Users\WDS>d:

D:\>cd dev/wdl

D:\dev\wdl>gradlew :1.14.4:build -x test
Starting a Gradle Daemon, 1 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :1.09.0
#################################################
         ForgeGradle 0.2.1-556330e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################

> Configure project :1.12.0
#################################################
         ForgeGradle 0.2.1-556330e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################

> Configure project :1.09.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.
#################################################
         ForgeGradle 2.2-SNAPSHOT-3966cea
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################

> Configure project :1.09.4-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.10.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.11.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.0-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.
#################################################
         ForgeGradle 2.3-SNAPSHOT-7764e3e
  https://github.com/MinecraftForge/ForgeGradle
#################################################
                 Powered by MCP
             http://modcoderpack.com
     by: Searge, ProfMobius, R4wk, ZeuX
     Fesh0r, IngisKahn, bspkrs, LexManos
#################################################

> Configure project :1.12.1-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.12.2-litemod
This mapping 'snapshot_20190708' was designed for MC 1.14.3! Use at your own peril.

> Configure project :1.14.1
New Dep: net.minecraft:client:1.14.1_mapped_snapshot_20190708-1.14.3

> Configure project :1.14.2
New Dep: net.minecraft:client:1.14.2_mapped_snapshot_20190708-1.14.3

> Configure project :1.14.3
New Dep: net.minecraft:client:1.14.3_mapped_snapshot_20190708-1.14.3

FAILURE: Build failed with an exception.

* What went wrong:
Project '1.14.4' not found in root project 'wdl'. Some candidates are: '1.09.0', '1.09.2', '1.09.4', '1.10.0', '1.10.2', '1.11.0', '1.11.2', '1.12.0', '1.12.1', '1.12.2', '1.14.1', '1.14.2', '1.14.3'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 44s

**Comment by Tsoccerguy3** [comment]
try running from the command line with --debug . maybe you are not getting the error if your IDE is able to fix errors on the fly

**Comment by Pokechu22** [comment]
Do you have the latest code?  Maybe you switched to an earlier revision or something.  The error you're getting now implies that the 1.14.4 project simply does not exist... but before, it did successfully find it (as indicated by it failing in `task :1.14.4:test` before).

Make sure that `settings.gradle` has the line `include '1.14.1', '1.14.2', '1.14.3', '1.14.4'` (and that that line includes 1.14.4), and also that `1.14.4/build.gradle` exists (well, and that the whole 1.14.4 folder exists; that's kinda important).

**Comment by Tsoccerguy3** [comment]
you were right this last time i compiled from my laptop , which i had not run , git pull , first .  my bad . It compiles . sorry . This was caused by loosing track of what I had done and on what computer .Thanks

Want me to close this issue as solved ?

**Comment by Pokechu22** [comment]
Sure.  I still need to fix those tests failing, but that's not directly part of this issue.

**Comment by Pokechu22** [comment]
I've fixed the issue with tests failing (I think; at least it's fixed for me), so you should no longer need to add `-x test` when building.
