### ISSUE TITLE
[1.13.2 basemod] Consistent "Invalid Session"

### ISSUE THREAD

**Issue by ThatGamerBlue** [Pokechu22/WorldDownloader#117]
I keep getting `Invalid Session (try restarting your game and launcher)` every time I try to join a server, even after restarting my PC.

Using mod-worlddownloader-baseedit-4.0.4.0-mc1.13.2.zip

**Comment by Pokechu22** [comment]
That sounds odd, particularly if it persists after restarting your machine.

A few things to try:

* Do you also have the same issue when running vanilla?
    * If it works with vanilla, does it break again when using WDL?
* Does it persist after logging out and back into the launcher?

**Comment by ThatGamerBlue** [comment]
No issues with vanilla, yes it persists.

edit: forgot to mention, I've tested four different servers, including a completely vanilla one I setup to test with.

**Comment by Pokechu22** [comment]
I can't reproduce it on my own machine (connecting to a local vanilla server).  So something's odd.

My guess is you did something weird with installation and modifying the JSON -- if some of the game arguments are missing, then the game can't authenticate properly.  But I'm not 100% sure about that.

**Comment by ThatGamerBlue** [comment]
Was just forced to reinstall my whole machine (broke something trying to
dual-boot ubuntu) so I'll try again later.
