### ISSUE TITLE
Menu Text Broken, MultiMC

### ISSUE THREAD

**Issue by NWBx01** [Pokechu22/WorldDownloader#121]
![2019-05-29_00 46 53](https://user-images.githubusercontent.com/21149527/58530106-6c6d3d80-81ab-11e9-8443-c548ddc78635.png)

All settings revert to this form when using OptiFine. As opposed to https://github.com/sp614x/optifine/issues/1286 this appears to be present for all versions of OptiFine on 1.12.2. From my testing, C5, C9, and E3 all experienced this issue.

**Comment by Pokechu22** [comment]
If you used the base edit, this is simply the nature of how those work and a conflict.  You shouldn't have this issue with the litemod, though.
