### ISSUE TITLE
cant find baseedit

### ISSUE THREAD

**Issue by mpg0907** [Pokechu22/WorldDownloader#124]
i im trying to get the 1.14.2 worlddownloader but it said you need baseedit to let it work but i cant find baseedit to download.

**Comment by Pokechu22** [comment]
In [release 4.0.5.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.0), it's `mod-worlddownloader-baseedit-4.0.5.0-mc1.14.2.zip`, which is at the very end of the list.

**Comment by mpg0907** [comment]
now i placed it in my mods folder but it doesnt work. im not that used to mods

**Comment by Pokechu22** [comment]
The installation process is a bit confusing, but you can find the documentation for it [on the forum thread](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation) (you specifically want to follow the base edit instructions using multimc).  The base edit version will not load from just putting it in the mods folder, unfortunately.

**Comment by mpg0907** [comment]
it worked but a small question is it possible to get the see dof the world too?

**Comment by Pokechu22** [comment]
No, that is not possible (other than the case where you already have permission to run `/seed`, in which case WDL will save the seed given by that command if you run it while downloading).
