### ISSUE TITLE
Doesn't work in 1.14.3

### ISSUE THREAD

**Issue by 19mdavenport** [Pokechu22/WorldDownloader#127]
I tried loading this into 1.14.3 and I couldn't load in any world

**Comment by Pokechu22** [comment]
I haven't yet finished updating it to 1.14.3.  I've got the start of a 1.14.3 build working, but I'm currently fixing the bugs and various build system issues.  It'll probably be done within the week.

**Comment by 19mdavenport** [comment]
Oh ok. Sorry. Thank you for making this!

**Comment by Pokechu22** [comment]
[Version 4.0.5.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.5.1) has just been released, which supports 1.14.3.
