### ISSUE TITLE
Project dont work !

### ISSUE THREAD

**Issue by Shyren** [Pokechu22/WorldDownloader#129]
Hey ! 
Im using muiltimc for load the mods and the mods dont work/load on minecraft 1.14.3

Whats the problem ?
![Capture](https://user-images.githubusercontent.com/52678299/60840404-6badcb00-a19d-11e9-8fc4-289b37a76d06.PNG)

**Comment by Pokechu22** [comment]
I see it's under "loader mods", which looks wrong to me.  Did you use "Add to minecraft.jar" to add the mod, or a different button?

**Comment by Shyren** [comment]
Omg thanks, i put the mods on the wrong button !
All work now ! big thanks
