### ISSUE TITLE
How to get world downloader for 1.14.4

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#139]
Sorry, I'm new to this github stuff. I've used the world downloader before and know all that, I just don't know how to get it past 1.12.2. I want to use it for 1.14.4 for a server but I can't seem to get it working.

**Comment by uyjulian** [comment]
Did you follow the instructions? https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation

"I can't seem to get it working" does not describe an issue we can help you with.

**Comment by ghost** [comment]
Lets see how can I explain it, I downloaded liteloader and world downloader but liteloader is only 1.12.2. Is there any other launchers that I can use World Downloader for 1.14.4?

**Comment by Pokechu22** [comment]
Yes, you install it as a base edit instead (which is a more crude method of modding, but it works for 1.14.4 and other versions where liteloader doesn't exist).  There's information in the forum post you were linked to; expand the base edit section.  The easiest way to install it is to use multimc.

(One other thing: make sure you're using the 1.14.4 version of the mod - there is no check to make sure you haven't mixed versions up and if you use, say, the 1.9 version of the mod, you'll get a rather cryptic crash.)

**Comment by felipekzbr** [comment]
> Yes, you install it as a base edit instead (which is a more crude method of modding, but it works for 1.14.4 and other versions where liteloader doesn't exist). There's information in the forum post you were linked to; expand the base edit section. The easiest way to install it is to use multimc.
> 
> (One other thing: make sure you're using the 1.14.4 version of the mod - there is no check to make sure you haven't mixed versions up and if you use, say, the 1.9 version of the mod, you'll get a rather cryptic crash.)

Pokechu22 do you have the instructions how i do that in the version 14.4.4? (install as a base edit). 
I tried just like the Installation instructions in minecraft forum but did not appear option to download the map ( i also tried with multiMC)?

**Comment by Mhowser** [comment]
Any possibility that WDL can be a Fabric mod for 1.14 versions?

Edit : found the discussion #133

**Comment by Pokechu22** [comment]
Closing this ticket as OP deleted their account and the question was answered.

**Comment by Atomiic101** [comment]
how do i get the base version for 1.14.4

**Comment by Pokechu22** [comment]
Go to the [releases](https://github.com/Pokechu22/WorldDownloader/releases) section, expand assets (if it's collapsed), and download the one matching your version.  For WDL version 4.0.6.0 (currently the latest) and 1.14.4, you want the one named `mod-worlddownloader-baseedit-4.0.6.0-mc1.14.4.zip`.
