### ISSUE TITLE
Can't download skyblock

### ISSUE THREAD

**Issue by Askejm** [Pokechu22/WorldDownloader#140]
Hello. I want to download my friend's skyblock island so that I can import it into Blender 3d. When I  try to download it I and get told to choose a world I can't select anything.
![image](https://user-images.githubusercontent.com/55248977/64799684-862d6780-d585-11e9-9402-72f52267e349.png)

**Comment by Pokechu22** [comment]
I'm assuming you already figured it out since you closed the issue, but you need to click "new name", type the world name, and then press enter.  The multiworld GUI is definitely confusing and it's something I've wanted to redo for a while but I haven't gotten around to it.
