### ISSUE TITLE
Feature Request: Allow Repositioning The Download World Button

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#147]

**Comment by Pokechu22** [comment]
The other buttons are supposed to be automatically shifted down ([relevant code](https://github.com/Pokechu22/WorldDownloader/blob/b1b279f948beec2d7dac7524eea8f584a866d8eb/share_14/src/main/java/wdl/WDLHooks.java#L602-L636)), but I'm guessing that there's some kind of weird initialization order thing going on there with how you've installed it (I'm surprised that it works that way, actually; I haven't tested that setup myself).  This will probably be resolved once there's an official fabric port (see #133; there is an unofficial port there but it actually has the same issue).

Note that you should be able to select the obstructed buttons with <kbd>tab</kbd>, but I'm pretty sure they're the "send feedback" and "report bugs" buttons and aren't applicable in a modded setup anyways.
