### ISSUE TITLE
1.15.1

### ISSUE THREAD

**Issue by Motovoh** [Pokechu22/WorldDownloader#148]
I would like you to release a version that is working for 1.15.1 :)!

**Comment by Pokechu22** [comment]
I'm working on it, with a release hopefully some time this year.

**Comment by Motovoh** [comment]
Any betas that you can roll out by end of the next week?

**Comment by Pokechu22** [comment]
I don't have anything ready yet, so I don't want to make any guarantees on that (I've found that I'm bad with deadlines).  As soon as I've got something that works and seems stable enough I'll release it though.

**Comment by Pokechu22** [comment]
I've released [Version 4.0.6.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.0), which includes support for 1.15 and 1.15.1.
