### ISSUE TITLE
How to install1.14.4

### ISSUE THREAD

**Issue by Harvey0921** [Pokechu22/WorldDownloader#149]
I don't know how to install the worlddownloader Mod
How to use mod-worlddownloader-baseedit-4.0.5.3-mc1.14.4.zip
I used to install ". litemod" directly in mod folder

**Comment by Pokechu22** [comment]
The current 1.14 builds are only available as a base edit; there are instructions [in the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation) but the simplest way of installing them is to use MultiMC and "Add to minecraft.jar".
