### ISSUE TITLE
Chest content is saved but its not an actual chest.

### ISSUE THREAD

**Issue by UniqueUserName500** [Pokechu22/WorldDownloader#150]
Hello, so currently I need to see through a few items attribute in the chest of some server, but they're only GUI so if I opened the GUI up while downloading the world, WDL said: "Chest content saved". But when in single-player, I really don't know how to find those chest coordinate or how they even saved or exists.

Any help or tips would be awesome. Thank you.

**Comment by Pokechu22** [comment]
I'm actually not sure where those are being saved.  Previously (in certain MC versions), a chest with no associated block could cause a game crash (#137).  I attempted a fix for that (7df1d1efa3eaf4dff0a5ca89e370d9cdacde873f) but it was a very quick fix that doesn't handle all underlying cases.

There isn't any real way to know what block a GUI is associated with, so WDL instead assumes (or is supposed to assume) that the block you were looking at when the GUI opened is the one associated with the GUI.  The *intended* behavior for chests with no blocks is to print a warning that there was no chest being looked at at the time.  (The same warning exists for moving the mouse away from the chest as you open it; this is easier to do with more latency).

My guess is that those chests are instead overwriting the contents of the last chest block you actually saved.  I haven't confirmed that, though.

If you want to intentionally save the contents of one of those chests to some chest in the world, you can place a chest block and, while looking at it, run whatever command is needed to open the fake chest.  WDL should then save the contents of the fake chest into the chest you placed.  After that, make sure not to look into or break that chest block until after you stop downloading (as doing either of those will also affect the one in the downloaded world).  You can get rid of it after you finish downloading, though.

**Comment by Pokechu22** [comment]
I've fixed handling of fake chests.  Now, if a chest is closed when you weren't looking at a chest when it was opened, it won't be saved and a message explaining that it wasn't saved will be put into chat.  (You should still be able to save these fake chests by looking at a chest block when you open them; it'll just not overwrite something else by accident).
