### ISSUE TITLE
Crash in combination with WWE when hitting ESC

### ISSUE THREAD

**Issue by PepeHands78** [Pokechu22/WorldDownloader#152]
**WWE version:** 3.0.4
**Minecraft version:** 1.12.2
**Operating system:** Windows 10 (64 bit)
**Other mods:** WWE

**Whats the issue:** 
1. Install Forge and LiteLoader
2. Install Litemod WorldDownloader version 4.0.6.0
3. Install WWE Client ( https://wweclient.com/ )
4. Launch Minecraft and play in a singleplayer or multiplayer environment
5. As soon as ESC is pressed, the game should crash

**Crash-report:**

https://pastebin.com/ejpwE8vw

**Additional notes:**
This occurs exactly as the Pause/ESC menu is built, so I assume it has something to do with the buttons by both WorldDownloader and WWE being created on the screen, one of them is causing a NullPointerException as far as I can read the crash report. Thanks in advance.

**Comment by Pokechu22** [comment]
I do not support clients designed for cheating.  This issue will not be investigated or fixed.  Sorry.
