### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by Nastrond88** [Pokechu22/WorldDownloader#153]
Hi! I need to download part of a 1.15.2 map, will the mode be updated soon? I can`t connect to the server with the 1.15.1 version!

**Comment by Pokechu22** [comment]
It's in progress.  I've got the basic code for 1.15.2 done already, and am currently working on resolving issues with it (and the build system).  I don't have any ETA.

**Comment by ReneSamajStudio** [comment]
Please relase WTD 1.15.2 **im need it for my work** :[

**Comment by Pokechu22** [comment]
I've been delaying because I want to get #133 done (and then delaying further because I'd already delayed for that and wanted something to show for it).  But it's been too long, so I'll just try to get 1.15 out today, since it's been long enough.

**Comment by aidancrane** [comment]
Thanks @Pokechu22. True dedication to your [mine]craft. </Badpun>

**Comment by Pokechu22** [comment]
I've released [v4.0.6.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.1), which supports 1.15.2.

**Edit**: and I just realized that I've made some mistakes with load order.  So while 4.0.6.1 works, I'll release a second version in a bit that fixes those problems.

**Comment by Pokechu22** [comment]
I've released [v4.0.6.2](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.6.2), which corrects some issues from v4.0.6.1.
