### ISSUE TITLE
The Connection Was Forcibly closed

### ISSUE THREAD

**Issue by afanofjapan** [Pokechu22/WorldDownloader#16]
When I join a certain server I get kicked with this error. The IP is towny.pandacraft.org Also, I think this error has to do with the Spigot plugin AAC, but I can not confirm this.![](http://i.imgur.com/ksr4HRe.jpg) EDIT: I looked more into this, and found out it is not a problem with AAC. In addition, I found out that it might be a problem with BungeeCord.

**Comment by Pokechu22** [comment]
I see some §-based codes in the log:

```
[16:28:31] [Client thread/INFO]: [CHAT] §A§n§t§i§M§i§n§i§m§a§p
[16:28:31] [Client thread/INFO]: [CHAT] §3 §6 §3 §6 §3 §6 §e
[16:28:31] [Client thread/INFO]: [CHAT] §0§0§1§2§3§5§e§f
[16:28:31] [Client thread/INFO]: [CHAT] §0§0§c§d§e§f
```

I _think_ I recognize that one.  Ah, yep.

It's got a kick message that works when the coremod version is used, but doesn't work when the litemod version is used.  I'm not entirely sure why it would differ like that, though.

**Comment by Pokechu22** [comment]
Whichever plugin is being used isn't the one I wrote, to clarify.  I don't like kicking players (far too confusing, and things like this end up happening).

**Comment by afanofjapan** [comment]
So is there something me or you could do to fix the kick?

**Comment by afanofjapan** [comment]
Nevermind

**Comment by Pokechu22** [comment]
Really, the easiest way to deal with it is to just talk to a server operator.  I don't know exactly what plugin they are using, but it would make sense to mention that to the author of the plugin as well (I'll have to look in to it at some point).

**Comment by afanofjapan** [comment]
Okay

**Comment by Pokechu22** [comment]
I've figured out which plugin is kicking (AntiMinimap) and [requested that the author use a method other than kicking](https://www.spigotmc.org/threads/antiminimap-bukkit-bungee.28538/page-7#post-1528049).  Closing issue now (there's other stuff that I have done relating to players getting kicked but I won't go into detail here).
