### ISSUE TITLE
I dont know what to do

### ISSUE THREAD

**Issue by xxclaireyx** [Pokechu22/WorldDownloader#161]
When i download this mod for 1.15.2 it isnt a jar file so it wont do anything. Any way to make it a jar file or solve it?

**Comment by Pokechu22** [comment]
Read [the installation instructions in the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation).  The 1.15.2 build is a base edit, so it's easiest to install it using multimc.  This (rather ancient) method of modding is incompatible with basically all other mods, so you'll want to use a clean install (easy enough with multimc).

I plan to port to other more conventional mod loaders when I have time.
