### ISSUE TITLE
Downloaded world won't show up in McEdit Unified and spawning in void when imported with multiverse

### ISSUE THREAD

**Issue by JellyNutShell2** [Pokechu22/WorldDownloader#165]
1.15.2 World. No mods. No multiverse. Not even on Fabric. The world opens in McEdit Unified, but nothing shows up besides the checker pattern.

Also getting issue #143 when I try to import a downloaded world with multiverse

**Comment by Pokechu22** [comment]
Does the world actually load correctly in single player?  And, after loading it in single player, does it load correctly with McEdit?

I haven't really been following McEdit, but I'm not sure if it targets worlds from 1.15; last I heard it was only compatible with 1.12 and earlier, and worlds from 1.13 and newer use a different world format that it doesn't understand.  I guess you could check that by creating a new world and trying to import that.

**Comment by JellyNutShell2** [comment]
> Does the world actually load correctly in single player? And, after loading it in single player, does it load correctly with McEdit?
> 
> I haven't really been following McEdit, but I'm not sure if it targets worlds from 1.15; last I heard it was only compatible with 1.12 and earlier, and worlds from 1.13 and newer use a different world format that it doesn't understand. I guess you could check that by creating a new world and trying to import that.

Yes. It works in single player. You're thinking of McEdit 2.0, McEdit Unified works with the new format. I tried and McEdit opens every other 1.15 world except the world download.

**Comment by Pokechu22** [comment]
Are you completely sure about that?  At least as far as I can tell, it doesn't support it: the website doesn't mention it all (the latest I see is 1.11.2); I see a bug report about 1.13 being unsupported; and I also see [code that warns that 1.13 is unsupported](https://github.com/Podshot/MCEdit-Unified/blob/90abfb170c65b877ac67193e717fa3a3ded635dd/pymclevel/infiniteworld.py#L1287-L1288).

One way to fully check if this is an issue with WDL would be to enable terrain generation (set it to something other than void in WDL's generator settings screen, and then stop download afterwards).  Then, in the downloaded world, generate new chunks, and see if those show up in McEdit.  (To fully control for errors, also teleport to say 2000, 2000 which should create a new region file (`r.3.3.mca`) completely untouched by WDL; I doubt that chunks in a new region file would actually behave differently from chunks in an existing region file but it's worth testing).

**Comment by JellyNutShell2** [comment]
> Are you completely sure about that? At least as far as I can tell, it doesn't support it: the website doesn't mention it all (the latest I see is 1.11.2); I see a bug report about 1.13 being unsupported; and I also see [code that warns that 1.13 is unsupported](https://github.com/Podshot/MCEdit-Unified/blob/90abfb170c65b877ac67193e717fa3a3ded635dd/pymclevel/infiniteworld.py#L1287-L1288).
> 
> One way to fully check if this is an issue with WDL would be to enable terrain generation (set it to something other than void in WDL's generator settings screen, and then stop download afterwards). Then, in the downloaded world, generate new chunks, and see if those show up in McEdit. (To fully control for errors, also teleport to say 2000, 2000 which should create a new region file (`r.3.3.mca`) completely untouched by WDL; I doubt that chunks in a new region file would actually behave differently from chunks in an existing region file but it's worth testing).

So the latest officially supported version is 1.12.2 but it still opens every other world in 1.15.2. I did this, and it's still empty in McEdit. In case theres an easier way to achieve what im looking for, what im trying to do is get a portion of a server saved as a .schematic.

**Comment by JellyNutShell2** [comment]
> > Are you completely sure about that? At least as far as I can tell, it doesn't support it: the website doesn't mention it all (the latest I see is 1.11.2); I see a bug report about 1.13 being unsupported; and I also see [code that warns that 1.13 is unsupported](https://github.com/Podshot/MCEdit-Unified/blob/90abfb170c65b877ac67193e717fa3a3ded635dd/pymclevel/infiniteworld.py#L1287-L1288).
> > One way to fully check if this is an issue with WDL would be to enable terrain generation (set it to something other than void in WDL's generator settings screen, and then stop download afterwards). Then, in the downloaded world, generate new chunks, and see if those show up in McEdit. (To fully control for errors, also teleport to say 2000, 2000 which should create a new region file (`r.3.3.mca`) completely untouched by WDL; I doubt that chunks in a new region file would actually behave differently from chunks in an existing region file but it's worth testing).
> 
> So the latest officially supported version is 1.12.2 but it still opens every other world in 1.15.2. I did this, and it's still empty in McEdit. In case theres an easier way to achieve what im looking for, what im trying to do is get a portion of a server saved as a .schematic.

Ok, the issue is with McEdit. I downloaded another program called Mineways and it did exactly what I was looking for.
