### ISSUE TITLE
[Suggestion] Option to identify players who using the Mod

### ISSUE THREAD

**Issue by MegaNoam** [Pokechu22/WorldDownloader#166]
**I don't know how much you take this offer seriously so I'll try anyway**
I suggest adding an **API** that server owners can use and prevent using Mod to prevent copying without server permission
If this exists, I'd love to know

**Comment by Pokechu22** [comment]
This exists already, see [the wiki.vg article documenting the API](https://wiki.vg/Plugin_channels/World_downloader).
