### ISSUE TITLE
I Dont Know How To Us MultiMC

### ISSUE THREAD

**Issue by beefyavocado** [Pokechu22/WorldDownloader#168]
I've tried just about everything I could think of.

**Comment by Pokechu22** [comment]
Can you provide some more information?  Are you confused about adding the mod to multimc, or starting the game with multimc, or is the game crashing when you start it?

**Comment by beefyavocado** [comment]
I did all of the steps that were in the forum and the button wasn't there when I joined a server. I'm trying to play 1.15.2

**Comment by Pokechu22** [comment]
Make sure to use the "Add to minecraft.jar" button in multimc, and not the "add mod" button; that's the most common reason something like this happens.

**Comment by beefyavocado** [comment]
Thank you, I realized I clicked the wrong folder :)

**Comment by Pokechu22** [comment]
I'm closing this issue, since it seems like you've got everything figured out.  If not, just reply.
