### ISSUE TITLE
Suggestion :)

### ISSUE THREAD

**Issue by craftish37** [Pokechu22/WorldDownloader#179]
Hi,
I've test your mod, and it's incredible, but I think a cool thing to add is the possibility to save chests items via the nbt or an other process, I'm on a survival server and lot of chests are locked, so I can't charge them :/

Do what you want with this idea,
Craftish :)

**Comment by uyjulian** [comment]
Chests can already be saved by opening them.
The server does not send the contents of the chest if it is not opened.
