### ISSUE TITLE
java.lang.NullPointerException: Updating screen events

### ISSUE THREAD

**Issue by MinecrafterTim12** [Pokechu22/WorldDownloader#18]
I have an issue with WorldDownloader_1.8.9a-beta1.

If I select download world, sets the multi world support to true and presses finish my client crashes with the following error log: http://pastebin.com/Fq3ur2jq
I hope that you can fix this error quick.

Kind regards
MinecrafterTim12

**Comment by Pokechu22** [comment]
Something tells me not all of the hooks have been applied.

Can you open the WDL about GUI (<kbd>...</kbd> &rarr; <kbd>About World Downloader</kbd>) and then select "Copy debug info", and then paste the results here?

**Comment by MinecrafterTim12** [comment]
Shure, here you are: [http://pastebin.com/n2ZjHm73](http://pastebin.com/n2ZjHm73)
But i have to disable multiworld support to get this information.
The error only appears when i have multiworld support enabled

**Comment by MinecrafterTim12** [comment]
And when i disabled Multiworld support i can download the world but when i click stop download the world my client crashes with the following crash report [http://pastebin.com/RYu1E0e8](http://pastebin.com/RYu1E0e8)

**Comment by Pokechu22** [comment]
This was fixed a long time ago - it was a threading issue that was my own fault, due to creating GUIs on the wrong thread (they were rendered before they were initialized).
