### ISSUE TITLE
Support 1.16.1

### ISSUE THREAD

**Issue by F4brizio** [Pokechu22/WorldDownloader#186]
Is a version compatible with minecraft 1.16.1 planned? When will it come out?

P.S. Thank you very much for your work.

**Comment by Pokechu22** [comment]
Duplicate of #180.  I'm working on it, and I'll hopefully have something ready before 1.16.2 comes out in a few days, but I can't promise it.

**Comment by Pokechu22** [comment]
https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.0.0

**Comment by F4brizio** [comment]
I love you ♥ Thank you
