### ISSUE TITLE
How do I download the 1.16 version mod?

### ISSUE THREAD

**Issue by amoraschi** [Pokechu22/WorldDownloader#188]
The only file that I found was a .zip, if you can explain to me what do I do next with that, I would appreciate it.

**Comment by Pokechu22** [comment]
You can install it using MultiMC with "add to minecraft.jar".  Follow the baseedit instructions in [the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation).

**Comment by amoraschi** [comment]
> You can install it using MultiMC with "add to minecraft.jar".  Follow the baseedit instructions in [the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-world-downloader-mod-create-backups-of-your-builds#Installation).

Thanks
