### ISSUE TITLE
1.15.2 crash online

### ISSUE THREAD

**Issue by bilbibalou** [Pokechu22/WorldDownloader#189]
When i join my online server minecraft crash with this message 

The game crashed whilst wdl mod: exception in onworldclienttick event
Error: java.lang.NoClassDefFoundError: net/minecraft/util/math/vector/Vector3d

it crash only online not in solo I use minecraft 1.15.2 forge v31.2.0  world downloader v4.1.0.0
there is no probleme with v4.0.7.0

**Comment by Pokechu22** [comment]
This is a known issue; for now, just use the v4.0.7.0 version.  v4.1.0.0 is mainly for 1.16 right now (I will fix Forge and other things in v4.1.0.1 or such).

**Comment by bilbibalou** [comment]
ok

**Comment by Pokechu22** [comment]
This issue should be fixed in [Version 4.1.0.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.0.1); please let me know if you still have problems.
