### ISSUE TITLE
Some sounds are no longer playing in 1.9

### ISSUE THREAD

**Issue by Pokechu22** [Pokechu22/WorldDownloader#19]
For some strange reason, certain sounds are not playing in 1.9.  I'm looking into why this is happening, but it's very odd.

The menu and block break sounds _do_ work.  Other sounds do not.  Interestingly, those sounds don't even generate a closed caption (while the menu and break ones do).

**Comment by WolfezzKyne** [comment]
Having this issue on any craftbukkit or spigot-server (non-vanilla-servers) without WorldDownloader or any mods too
I don't think it's a WD issue

**Comment by Pokechu22** [comment]
It _was_ a WDL issue initially.  I fixed it in 89e2f166.  Before, even on vanilla servers, some sounds would not play at all.

Most likely, that's a separate issue.  What sounds, if any, are you hearing?  I'm tempted to guess that you've got the wrong sound index associated with your version.

**Comment by Pokechu22** [comment]
It might also be a case of a protocol hack messing up sound events (protocol hacks are what allow 1.9 clients to connect to 1.8 servers).
