### ISSUE TITLE
Half words

### ISSUE THREAD

**Issue by MinetopiaFan135794** [Pokechu22/WorldDownloader#194]
Hello i have a issue,
when i download a world from a server
t takes a long time to download so I disconnect then I have a single player world but it is half so I get half world I think it is because I stop halfway but my question is do you get a message if it succeeded orz otherwise the download continues for hours. and you have to have everything you want to download loaded first so you have to be there?
![2020-11-12_19 16 42](https://user-images.githubusercontent.com/73842089/98980384-d521b480-251c-11eb-8948-0c5f7eef8724.png)

**Comment by Pokechu22** [comment]
The only areas that get saved are the areas you _visit_ while downloading (you should walk around, and also open chests and other containers if you want to save their contents).  There is no message saying you are done downloading; you need to decide when you've downloaded all of the parts of the world you care about.  Once you are done, click the "stop download" button, and it will save.

**Comment by MinetopiaFan135794** [comment]
THX
