### ISSUE TITLE
Load all chunk in 1 try

### ISSUE THREAD

**Issue by MinetopiaFan135794** [Pokechu22/WorldDownloader#195]
Is it possible to download the world WITHOUT going anywhere

**Comment by DrMoraschi** [comment]
No

**Comment by MinetopiaFan135794** [comment]
It may take time, but just that I don't have to walk all over my building

**Comment by Pokechu22** [comment]
If you need to save more parts of the world than are in your view distance (when you first join the server), you'll need to walk around.  If your building fits within the part of the world that you can already see, then you don't need to walk around.  If your building is very large, you may still need to walk about; you don't need to enter every chunk though (they just need to go within view distance).  The "saved chunks" GUI may help (though it doesn't show things that are currently loaded and will be saved when you stop downloading).

**Comment by MinetopiaFan135794** [comment]
THX
