### ISSUE TITLE
Lite Loader Version

### ISSUE THREAD

**Issue by afanofjapan** [Pokechu22/WorldDownloader#2]
Hey, if you want I could port your version of World Downloader 1.8 to Lite Loader 1.8. May I?

**Comment by Pokechu22** [comment]
Sure, go ahead.

**Comment by afanofjapan** [comment]
Okay. I will.

**Comment by Pokechu22** [comment]
Though make sure that you include the plugin channel stuff in your version (see [these changes](https://github.com/Pokechu22/WorldDownloader/compare/9f7b561d9bc6712dfe3cb320e98d507b6b6b9ece...b624dbeba81a8ff5fa8ff152e98990fb57cbf9d5)).  That feature's not used yet, but it seems like something that should be on both versions.

**Comment by afanofjapan** [comment]
Oh okay. Thank you, I will be sure to do that.

**Comment by afanofjapan** [comment]
Why did you close this Issue?

**Comment by Pokechu22** [comment]
I closed it since the question you asked is answered and I don't really think we need to keep it on the current issues list.  It doesn't mean that you should stop working on anything.

**Comment by afanofjapan** [comment]
Oh okay =)
