### ISSUE TITLE
Remove Holographic text option?

### ISSUE THREAD

**Issue by DatScreamer** [Pokechu22/WorldDownloader#20]
How to remove it?

**Comment by Pokechu22** [comment]
The extension is built-in (partly as an example as to how one would write an extension); don't worry about it too much.

There currently isn't a way to disable individual extensions, although it's a planned function.

If you have holograms and armorstands both enabled in entity potions, then the extension makes no difference.  The only point of the extension is to allow individually disabling holograms without effecting other entities: if you leave all entities enabled then it makes no changes.

**Comment by Pokechu22** [comment]
You can now turn off individual extensions in the latest release.

**Comment by DatScreamer** [comment]
thanks
