### ISSUE TITLE
World is saved but does not end up in backups folder

### ISSUE THREAD

**Issue by Duffilufagus** [Pokechu22/WorldDownloader#205]
It's exactly as the the title says, 1.16.4 server. Everything goes fine with the download, no errors whatsoever and the file just never shows up in the backups folder. Any ideas?

**Comment by Pokechu22** [comment]
Does it show up in the saves folder, though?  And, do you get the toast showing that the world was backed up after you finish saving?  If it is saved but the toast doesn't show up, you might have disabled the backup function (though that doesn't seem like something you could easily do by accident).

**Comment by Duffilufagus** [comment]
lol you're right, the worlds are being put in "saves." The first download I tried went to backups oddly enough, but hey at least we know what happened. Appreciate the help!

**Comment by Pokechu22** [comment]
Odd; normally, worlds should be put in both saves and backups.  One thought I had was that you were looking in the wrong backups folder (e.g. the normal .minecraft one instead of one from multimc), but if the first download went into backups, that doesn't make sense.
