### ISSUE TITLE
Could you make Extension with RedProtect Plugin??..

### ISSUE THREAD

**Issue by interlope7** [Pokechu22/WorldDownloader#21]
Im really love your WDL companion Plugin.. However.. more Suggestions..

Could you make Extension with RedProtect (Chunk OverRide..) like faction,worldguard..
And also Im using RedProtect plugin..

Please.. 

RedProtect plugin is open source so you can make it easier than ever..
Here the link

https://www.spigotmc.org/resources/redprotect-1-7-1-8-1-9-anti-grief-server-protection.15841/
and SRC

https://github.com/FabioZumbi12/RedProtect

**Comment by Pokechu22** [comment]
Sure, I'll look into it.

FYI, I prefer WDLCompanion requests in the [WDLCompanion repository](https://github.com/Pokechu22/WorldDownloader-Serverside-Companion/issues), but it's not too big of a problem.

**Comment by Pokechu22** [comment]
Done (a while ago) - https://github.com/Pokechu22/WDLCompanion-RedProtect
