### ISSUE TITLE
gap between saved and generated areas

### ISSUE THREAD

**Issue by SebiTimeWaster** [Pokechu22/WorldDownloader#213]
![gap](https://user-images.githubusercontent.com/3726309/108041138-72214b80-703e-11eb-9835-0b1bce8931bb.png)

between the area i walked and the generated area (by seed) there is a gigantic band that is not populated at all

version "mod-worlddownloader-baseedit-4.1.1.0-mc1.16.4.zip"
Minecraft 1.16.4
MultiMC v4.1.1.0
Java OpenJDK v11.0.10
Pop! OS 20.10

**Comment by waltersamson** [comment]
I think it's probably because you've visited the downloaded world before setting the seed, thus generating void chunks there.
