### ISSUE TITLE
Base-edit isn't applying for my MultiMC instance

### ISSUE THREAD

**Issue by VideoGameSmash12** [Pokechu22/WorldDownloader#214]
Howdy.

This is a somewhat complicated situation so here's what you need to know before I get into the details:
* The instance I'm trying to run this mod with MultiMC uses Fabric.
* Since I use the ModMenu mod, I used the pause menu deformities caused by a conflict between the two mods to determine whether or not the mod was actually active.
* I am aware of the mod's incompatibilities with certain other mods that I will note below, however their presence isn't causing this problem as the tests below show.
* I have verified that I installed the mod correctly, as the "Versions" menu lists the mod in there:
![https://videogamesm12.me/7Ba7Lpwwcj3B.png](https://videogamesm12.me/7Ba7Lpwwcj3B.png)

The issue I'm running into is quite simple: despite applying WorldDownloader as a base-edit mod, the mod does not appear to apply. A symptom I've encountered is my pause menu *not* looking deformed when I press ESC despite having the ModMenu mod, as shown here:
![https://videogamesm12.me/WVSBYrphsqer.png](https://videogamesm12.me/WVSBYrphsqer.png)

With the mods I use, the pause menu is expected to look like this instead:
![https://videogamesm12.me/TgSiNBpVoX5i.png](https://videogamesm12.me/TgSiNBpVoX5i.png)

Here's the testing I did on a separate instance (which for some reason worked) and their results ("worked" means the deformities were present):
| Test Description | Result |
| --- | --- |
| Ran Fabric itself and WDL only | Worked |
| Did the same as above, but with all the other mods I use as well | Worked |
| Did the same as above, but also imported the configurations from my problematic instance | Worked |
| Did the same as above, but with the resource packs I use | Worked |
| Did the same as above, but with the shader packs I use for OptiFabric | Worked |

Here are the other mods I use:
![https://videogamesm12.me/KRe3AQhrnRp5.png](https://videogamesm12.me/KRe3AQhrnRp5.png)

I have no idea if the problem is caused by my MultiMC instance itself or not, but what I do know is that something isn't working or applying right. What should I try to do to fix the problem?

**Comment by Pokechu22** [comment]
Hi, thanks for the detailed report (and sorry for not responding for a while; I've been busy).

If I'm understanding correctly, you've attempted to add WDL (as a base edit) to your existing fabric install, but it didn't show up; furthermore, when trying to reproduce it with a new install that matched the first one, it _did_ show up.  And the way you tested whether it showed up was whether the download button was present in some way (even though it didn't ever align perfectly).

Fabric isn't something I'm currently supporting, and that it works semi-correctly as a base edit is still somewhat surprising to me.  My main recommendation would be to use a separate profile when you need to use WDL, sticking with your main profile for everything else.

But to try and diagnose it: you can also check whether WDL loaded by forcing a crash; there should be an extra section in the crash report related to it.  Granted, with the base edit, I can't guarantee that this loads right when combined with mods at all (and in particular looking at your modlist, "Not Enough Crashes" may also conflict with that (I don't know what it actually does)).  But if it shows up in the crash report in your main profile but not in the pause menu, that might indicate some kind of load order issue or conflict with the pause menu.

**Comment by VideoGameSmash12** [comment]
Sorry for the delay. I have literally no idea why but when I used a different instance that had the exact same mods, it worked. This can be closed, though I will probably never figure out why it wouldn't apply correctly for that particular instance.
