### ISSUE TITLE
How to install at 1.16.4

### ISSUE THREAD

**Issue by Misio12320** [Pokechu22/WorldDownloader#216]
Hello. I need support. How to install at 1.16.4 via MultiMC? I have installed in "Loader mods" and when I launch the game the downloader does not show in mp.

**Comment by Pokechu22** [comment]
If you are installing the forge version, you need to first install forge in the `version` tab, and then add `WorldDownloader-forge-4.1.1.0-mc1.16.4.jar` to the loader mods section.

If you are instead installing the base edit version, you can't use the loader mods section; instead, you need to use "Add to minecraft.jar" with `mod-worlddownloader-baseedit-4.1.1.0-mc1.16.4.zip`.
