### ISSUE TITLE
litemod [Help]Build Failed

### ISSUE THREAD

**Issue by StarDream521** [Pokechu22/WorldDownloader#217]
Is something wrong with me?
These links are no longer accessible

D:\WorldDownloader-4.1.1.0>gradlew install
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.9/userguide/gradle_daemon.html.
Dae
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\WorldDownloader-4.1.1.0\build.gradle' line: 28

* What went wrong:
A problem occurred evaluating root project 'WorldDownloader-4.1.1.0'.
> A problem occurred configuring project ':1.09.0'.
   > Could not resolve all artifacts for configuration ':1.09.0:classpath'.
      > Could not find pokechu22.test.begradle:begradle:0.2.7.
        Searched in the following locations:
          - file:/C:/Users/Administrator/.m2/repository/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7.pom
          - file:/C:/Users/Administrator/.m2/repository/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7-fg2.jar
          - https://repo.maven.apache.org/maven2/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7.pom
          - https://repo.maven.apache.org/maven2/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7-fg2.jar
          - https://oss.sonatype.org/content/repositories/snapshots/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7.pom
          - https://oss.sonatype.org/content/repositories/snapshots/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7-fg2.jar
          - https://files.minecraftforge.net/maven/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7.pom
          - https://files.minecraftforge.net/maven/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7-fg2.jar
          - https://jcenter.bintray.com/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7.pom
          - https://jcenter.bintray.com/pokechu22/test/begradle/begradle/0.2.7/begradle-0.2.7-fg2.jar
        Required by:
            project :1.09.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by Pokechu22** [comment]
You need to use `gradlew install` in the [ForgeGradle-extensions](https://github.com/Pokechu22/ForgeGradle-extensions) repo, not the main WDL repo.

**Comment by StarDream521** [comment]
Oh yes 
I use gradlew install in ForgeGradle-extensions
Has been completed 
Excuse me, where do you put him next?
Where to use gradlew setupDecompWorkspace build
From Google Translate, the meaning may be wrong, please forgive me

**Comment by Pokechu22** [comment]
You use `gradlew setupDecompWorkspace build` in the `WorldDownloader-4.1.1.0` folder.

**Comment by StarDream521** [comment]
[err.txt](https://github.com/Pokechu22/WorldDownloader/files/6128673/err.txt)
After I enter gradlew setupDecompWorkspace build
Use gradlew :1.11.2-litemod:build
 Failed
Could you please see what went wrong

**Comment by Pokechu22** [comment]
I don't know what went wrong there.  `程序包mcp不存在` makes me think that libraries (库) were not added correctly, so try `gradlew :1.11.2:clean :1.11.2:setupDecompWorkspace :1.11.2:build`.

**Comment by Pokechu22** [comment]
I don't know what went wrong there.  `程序包mcp不存在` makes me think that libraries (库) were not added correctly, so try `gradlew :1.11.2:clean :1.11.2:setupDecompWorkspace :1.11.2:build`.
