### ISSUE TITLE
Crash when joining singleplayer

### ISSUE THREAD

**Issue by Nixinova** [Pokechu22/WorldDownloader#220]
Joining a singleplayer world crashes WorldDownloader.

- Forge version: 34.1.42
- Mod version: WorldDownloader-forge-4.1.0.2-mc1.16.3
- Game version: 1.16.3
- Other mods: OptiFine_1.16.3_HD_U_G3

[Crash log](https://github.com/Pokechu22/WorldDownloader/files/6276159/crash-2021-04-08_17.01.50-client.txt)
<details><summary>Log preview</summary>

```log
java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.compareNamespaced(Lnet/minecraft/util/ResourceLocation;)I
	at net.minecraftforge.registries.ForgeRegistry$Snapshot.lambda$static$0(ForgeRegistry.java:844) ~[forge:?] {re:classloading}
	at java.util.TreeMap.compare(Unknown Source) ~[?:1.8.0_231] {}
	at java.util.TreeMap.put(Unknown Source) ~[?:1.8.0_231] {}
	at net.minecraftforge.registries.ForgeRegistry.lambda$makeSnapshot$3(ForgeRegistry.java:820) ~[forge:?] {re:classloading}
```
</details>

**Comment by Pokechu22** [comment]
I'm not sure what to make of this.  None of the code in the main stacktrace is from WDL, so it probably isn't a WDL issue, but all of the relevant code is in Forge itself.  Forge [adds](https://github.com/MinecraftForge/MinecraftForge/blob/c0e74bc8a8ae68ec07c30e86fc11284a18135bec/patches/minecraft/net/minecraft/util/ResourceLocation.java.patch) the `compareNamespaced` function (and first added it in [this commit](https://github.com/MinecraftForge/MinecraftForge/commit/37f226eda597b42893049507f8fca6b94ba6f700#diff-bbd36f07830832fef2e2b6966ceeae46e13255bd93cb237cea485638e033b792) on Oct 9, 2020, corresponds to 1.16.3-34.1.16), so it shouldn't be affected by obfuscation-related problems, and started using it in ForgeRegistry in [this commit](https://github.com/MinecraftForge/MinecraftForge/commit/7d00d015f3b6000c68f7e5fa1fda9777042d4114) on Nov 1, 2020 (that commit corresponds to 1.16.3-34.1.42).  So, maybe try 1.16.3-34.1.41 and see if that works?

Normally I'd blame optifine for something like this, but I don't know how optifine would manage to break a method both added and used by forge.

**Comment by Nixinova** [comment]
Hmm, it does seem to be an OptiFine issue. Without it the world loads fine.
