### ISSUE TITLE
Crash report, 1.16.4. Error while launching. 

### ISSUE THREAD

**Issue by QuartzWarrior** [Pokechu22/WorldDownloader#226]
Not sure if I should upload my logs here, but I will give some details.

Using: MultiMC 5

Version: LWJGL 3 v3.22, Minecraft v1.16.4, Optifine 1.16.4 (custom), WDL baseedit 1.16.4 (custom), Intermediary Mappings 1.16.4, Fabric Loader v0.11.6.

Loader Mods: Replay Mod 1.16.4 v2.5.2

**Comment by QuartzWarrior** [comment]
Just did a bit of digging I guess and realized it only happened when I had the Replay Mod enabled, so prolly not ur thing...

**Comment by Pokechu22** [comment]
The base-edit version isn't expected to be compatible with other mods (which doesn't mean that it won't ever work, it's just that the way it's made means that it's likely to conflict).  There is a forge build (which is more likely to be compatible), but currently not a fabric one (sorry).

WDL and replay mod hook into similar things, so I'm not surprised that they'd conflict.  (Optifine also caused conflicts in the past, but I guess you're not running into issues with it?)

**Comment by QuartzWarrior** [comment]
Ok tysm, extremely fast response too lol, Optifine is working fine with it, thanks tho!
