### ISSUE TITLE
the download of the litemod version of the mod for 1.7.10 does not work

### ISSUE THREAD

**Issue by TheBeast434** [Pokechu22/WorldDownloader#230]
the download of the litemod version of the mod for 1.7.10 does not work

**Comment by Pokechu22** [comment]
The links are all archived and can be accessed by prefixing them with https://web.archive.org/web/1/ (for instance, https://web.archive.org/web/1/https://bintray.com/artifact/download/uyjulian/MinecraftMods/mod_WorldDownloader_8d05de448a5d76e4ec3acb325b8f641166fa158d_mc1.7.10.litemod).  I'll update the links in the forum post later today hopefully.

**Comment by TheBeast434** [comment]
thank you

**Comment by Pokechu22** [comment]
The forum thread links have been updated.
