### ISSUE TITLE
Add a 1.9.4 port

### ISSUE THREAD

**Issue by Masonrf** [Pokechu22/WorldDownloader#24]
This is just a suggestion to add a 1.9.4 specific version instead of only a 1.9 version of wdl. This would be extremely helpful since some servers that have updated to 1.9.4 do not allow any previous versions to join. I'm not too sure how difficult it would be to update, so if it's not possible in the near future, just say so.

**Comment by Pokechu22** [comment]
I'm already working on this, and it hopefully should be released either today or tomorrow!

**Comment by Masonrf** [comment]
Oh yeah I was about to edit my post as I read through a previous issue and saw you were planning on releasing a new version. Thanks! :D

**Comment by Pokechu22** [comment]
Done!  https://github.com/Pokechu22/WorldDownloader/releases/tag/1.9.4a-beta1
