### ISSUE TITLE
game crashes when saving world

### ISSUE THREAD

**Issue by Adamsmashem** [Pokechu22/WorldDownloader#241]
The game crashed whilst world downloader mod: saving world
Error: java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / minecraft:mountains]
Exit Code: -1

this only happens on one server (minehut.com)
the downloader works fine on other servers
I want to do stuff with the lobby and it would be nice to download it.
Ant help would be appreciated!

**Comment by Pokechu22** [comment]
Sounds like the same issue as #239.  Can you try the 1.16.1 version of the mod?

**Comment by Adamsmashem** [comment]
thanks for the quick replay! I cant get th1 1.16.1 version working because the download site (https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.1.1.0) has it as a .zip file wicth I have no idea how to get it to work.

**Comment by Pokechu22** [comment]
There are instructions in the minecraftforum post, but the short explanation is that the easiest way is to use MultiMC and "Add to minecraft.jar" to install it.

**Comment by Adamsmashem** [comment]
MultiMC doesn't work for me ether. idk why. My pc sucks

**Comment by Adamsmashem** [comment]
I got 1.15.2 to work wicth is fine for me. Thanks for the help!
