### ISSUE TITLE
Does it support fabric when 1.18.1 comes out?

### ISSUE THREAD

**Issue by GoodGolem** [Pokechu22/WorldDownloader#246]
I would like to see a fabric version for 1.18.1 since most 1.18.1 players use fabric as a mod loader.

**Comment by Pokechu22** [comment]
That is the plan, yes.

**Comment by vanquishingtide** [comment]
A fabric version would certainly be appreciated.

**Comment by GoodGolem** [comment]
Tq i found this github back just now bc i lost the link! XD
