### ISSUE TITLE
I appear in the void with a mode Cubic Chunks

### ISSUE THREAD

**Issue by ListVB** [Pokechu22/WorldDownloader#247]
I have a problem, after successfully loading the world from the server, I just appear in the void, I do not see the loaded world.
I am using mode cubic chunks.
Sorry, about English, i am using Google Translate

**Comment by Pokechu22** [comment]
Cubic Chunks changes the world format significantly.  It's unlikely that World Downloader will ever work properly with Cubic Chunks.  However, you might be able to use schematica/litematica to save parts of the world.

**Comment by ListVB** [comment]
What is the schematiса/litematica?

**Comment by Pokechu22** [comment]
https://www.curseforge.com/minecraft/mc-mods/litematica

**Comment by ListVB** [comment]
Thank you!

**Comment by Pokechu22** [comment]
Closing this since I answered your question. If you need more help, I can reopen the issue report (though I am not too experienced with litematica and can't help you with it).
