### ISSUE TITLE
[Bug] Leaf Decay , Not saving all maps and items in frames

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#252]
Not sure if these issues are handled with gamerules in 1.12.2 . The 1st bug is leaf decay . sometimes a servers worldgard setting is stopping the leaf decay on custom trees , I have seen trees made up of leaves , fences , gates and other blocks that can cause the game to begin to start leaf decay , because there are no logs attached . setting game ticks from 3 to 1 would cause other things to not work . could you add a setting to flip the NBT data bit for leaves to make them creative so they don't decay.

Not sure if this situation is handled , The usage of large amounts of Maps in frames . Generally placed picture data using Image to map.
 If there is heavy usage of maps in frames , should the maxentity craming  be set higher to allow the saving of more item frames and its contents ? as it is now , I dont know whay not all the Frames and its contents dont get saved

**Comment by Pokechu22** [comment]
An option to replace one block state with another block state would be useful (but I'm not sure how easy it would be to implement for general purposes).  You might also be able to use [MCASelector's ReplaceBlocks function](https://github.com/Querz/mcaselector/wiki/NBT-Changer) (something like `oak_leaves={Name:"minecraft:oak_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},spruce_leaves={Name:"minecraft:spruce_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},birch_leaves={Name:"minecraft:birch_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},jungle_leaves={Name:"minecraft:jungle_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},acacia_leaves={Name:"minecraft:acacia_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},dark_oak_leaves={Name:"minecraft:dark_oak_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},azalea_leaves={Name:"minecraft:azalea_leaves",Properties:{persistent:true,distance:7,waterlogged:false}},flowering_azalea_leaves={Name:"minecraft:flowering_azalea_leaves",Properties:{persistent:true,distance:7,waterlogged:false}}` would probably work, but I haven't tested it).  Also note that you would have to set randomTickSpeed to 0, not 1, for leaf decay to not happen.

Entity cramming doesn't cause item frames not to be saved.  It only applies to the number of entities within a 1x1x1 space (more or less), and I'm not sure if it applies to item frames at all (it doesn't apply to dropped items, for instance; I think it might only apply to entities that push other entities).  Most likely, you're running into an entity tracking range issue; try setting the tracking range to a smaller number for item frames.

**Comment by Tsoccerguy3** [comment]
tested 1.12.2 and 1.16.5 . I tried adjusting the tracking distance  . the messed up picture with the map images , are from item frames hundreds of blocks away . this is a common bug but doesn't happen all the time. 

somehow , the map images are getting named wrong or the co-ords are getting stored wrong

**Comment by Pokechu22** [comment]
Hmm, that's a different issue than I thought it would be.  That looks like the server might be re-using the IDs for map images in different areas, so when you visit a different area the map image ends up getting overriden.

The different maps are on the same world, right?  As in, you can walk between them without a dirt screen showing up?

**Comment by Tsoccerguy3** [comment]
The best way is to experience the issue IP , main.mcparks.us . Try walking around at warp mk north to south east to west . Tested with ticks at 0 , save in creative log off and check backup map for item frame problems . some item frames will vanish at 64 blocks . small items have a tracking distance of 4 blocks before vanishing.

**Comment by Tsoccerguy3** [comment]
one other thing , type /audio for audio. can the audio be saved ?

**Comment by Tsoccerguy3** [comment]
I tried starting and stopping in various areas , to see if it could get the proper contents . That issue just gets moved to other areas  . maybe there is a way to give the data a new name if the map date ID's are being reused . I never seen this before and I do not know how the wrong ID gets used. Try this version , I get less lag using 1.12.2 .

**Comment by Pokechu22** [comment]
> maybe there is a way to give the data a new name if the map date ID's are being reused .

That seems like what's needed, but I don't know how to do it.  In particular, detecting that versus an animated map, versus the same map in two different item frames seems difficult, and keeping track of what IDs have been used between downloading sessions also would be problematic.

You could save each section of the world under a different name (e.g. using the multiworld support functionality), but then you'd have a bunch of separate worlds that would be hard to combine together.

> one other thing , type /audio for audio. can the audio be saved ?

That's probably from a resource pack.  I think those are cached somewhere in .minecraft (possibly the resourcepacks folder, but it might be a separate folder), but I'm not 100% sure.

**Comment by Tsoccerguy3** [comment]
Minecraft is becoming more and more complex . That server is probably using viaversion because it accepts 1.12.2 up to 1.18.2 . The /audio command opens the browser to a audio server. the cue points or triggers are on the map and sent to the browser . the item frame issue changes spots depending where I start . which makes me think its not the ID's . I could use FAWE to save schematics using the -e switch on trouble areas then later paste them into correct areas . It would mean going back to problem areas and starting and stoping to get a corrected area . Yes there are animated armor stands and slide shows using item frames with maps, only the last grab is saved . These are controlled with command blocks and no way to grab commands yet
