### ISSUE TITLE
Crashes in 1.19

### ISSUE THREAD

**Issue by ghost** [Pokechu22/WorldDownloader#257]
Probably just needs an update

**Comment by TheTechRobo** [comment]
There's no official 1.19 build that I can tell. There isn't even a 1.18(.[12])? build yet.

**Comment by Pokechu22** [comment]
Indeed, there isn't a 1.19, 1.18, or 1.17 build yet.  How are you trying to use it in 1.19?

**Comment by mharbb** [comment]
wrong github project lmao sorry

**Comment by ghost** [comment]
wront github project sorry lmao
