### ISSUE TITLE
looking for WDL 1.6.4

### ISSUE THREAD

**Issue by bstar16** [Pokechu22/WorldDownloader#261]
i tried downloading the 1.6.4 release from the old minecraft forum but its just an endless adfly link so i came here since it says it was also available here but cant seem to find it anywhere

**Comment by Pokechu22** [comment]
You should be able to find it [here](https://github.com/Pokechu22/WorldDownloader/blob/a00522311230da90d6c838218f5ac758b0778bcf/bin/World%20Downloader%20%5B1.6.4%5D%2020130923.zip) (and in general, older versions can be found from starting [here](https://github.com/Pokechu22/WorldDownloader/commits/173c2738355297688e4bc80397ed89bf58976ec2), selecting the "browse the repository at this point in history" button ![image](https://user-images.githubusercontent.com/8334194/176938942-d1521e9e-2810-4790-b9cd-96991e456ece.png), and then looking in the `bin` folder, assuming it exists, and using the `zip` file if it exists and seems to be more recent).

**Comment by bstar16** [comment]
thanks for the help i ended up just opening the adfly link on my phone from the old forum since it wouldn't work on my pc and just download it from there

**Comment by Pokechu22** [comment]
Alright, glad you got it working, then.
