### ISSUE TITLE
WDL posted to Curse , Should be reported to Curseforge and removed

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#263]
Someone posted WDL to the Curseforge page here https://www.curseforge.com/minecraft/mc-mods/world-downloader-mod .
you may want to report it and have it removed . I decompiled it and it is 2 versions repacked

**Comment by Pokechu22** [comment]
The uploader there emailed me, and now that the version information has been corrected and a link to the main forum post and the source code has been added, I'm fine with this being there. I've added it to https://pokechu22.github.io/WorldDownloader/redistribution.html.
