### ISSUE TITLE
java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / minecraft:mountains]

### ISSUE THREAD

**Issue by Antonio225t** [Pokechu22/WorldDownloader#271]
I've tried to download a miltiplayer world that is currently using ViaVersion plugin (the hacklib to make minecraft multiple versions client to play in the same server). Is there a way to fix it (maybe by setting all the biomes to save as planks if the biome is not found??) Thank you so much in advance 👍.

**Comment by Pokechu22** [comment]
Try using an earlier 1.16 release of WDL (assuming ViaVersion allows it). There was something that changed later on in 1.16 with biomes that causes issues.

**Comment by Antonio225t** [comment]
Ah, I'm using 1.16.4 Forge version. Sorry I forgot to say this important part.

**Comment by Antonio225t** [comment]
Ok I tried with 1.15.2 and it worked. Thank you so much!
