### ISSUE TITLE
Damaged  map

### ISSUE THREAD

**Issue by zsy0073** [Pokechu22/WorldDownloader#276]
Can this mod be used in a large mod package? I used it on a mod server and got a damaged map. The world looks like it's made up of void and many fragments.

**Comment by Pokechu22** [comment]
Other mods may or may not work properly (especially more complex mods). It also depends on your Minecraft version and the mod loaders.

Can you post a screenshot? There's several different things that a world made up of void could be and a screenshot would help me determine if there's a way for you to work around the issue or not.

**Comment by zsy0073** [comment]
Thank you

https://github.com/Pokechu22/WorldDownloader/assets/109189490/de49ce41-f827-4324-bd62-08e921fba818

The modpack has over 300 mods. 
These strangely arranged stones did not exist in the original block.

**Comment by Pokechu22** [comment]
Yeah, that looks like the list of block IDs associated with each mod isn't properly being saved or something like that, resulting in a completely broken world. Unfortunately I don't think there's any way for you to work around it, WDL just won't be able to save stuff properly.

You could try using schematica/litematica maybe (which would produce schematic files of smaller parts of the world you can then paste into a new world, but wouldn't be able to save container contents).

**Comment by zsy0073** [comment]
Oh, thank you.
