### ISSUE TITLE
Add a category on the Readme.md listing alternative mods/programs for modern versions at least until this mod is updated to work on modern versions (Merge Pull Request #282)

### ISSUE THREAD

**Issue by The-Nyla** [Pokechu22/WorldDownloader#281]
It would be nice to have both https://github.com/Avanatiker/WorldTools (Fabric/Forge mod for 1.20.1) and https://github.com/mircokroon/minecraft-world-downloader (external program) added as possible alternatives to WDL on the readme.ml so people can more easily find functioning WDL mods for modern versions while waiting for this mod to update.

**Comment by The-Nyla** [comment]
made a pull request to make these changes (#282)

**Comment by Pokechu22** [comment]
Resolved by #282
