### ISSUE TITLE
1.10 support

### ISSUE THREAD

**Issue by bmintz** [Pokechu22/WorldDownloader#29]

**Comment by Pokechu22** [comment]
It'll happen as soon as I get the tools to make an MCP version for 1.10 (which means either I get a 1.10 build of MCP directly, or get an SRG file for 1.10 and make it work with 1.9.4 MCP).

I've got some ideas for how a minimal version of the mod could be done without MCP, but that would involve working directly against the bytecode (which I can do) and finding obfuscated classes (which I can also do, it's just not particularly easy).  But getting a version of MCP would be the most important step in releasing a 1.10 build.

**Comment by Pokechu22** [comment]
I've gotten a [1.10 SRG file](http://mcpbot.bspk.rs/mcp/1.10/mcp-1.10-srg.zip), so hopefully I can get something out today.

**Comment by Pokechu22** [comment]
https://github.com/Pokechu22/WorldDownloader/releases/tag/1.10a-beta1
