### ISSUE TITLE
WDL Show System Text, Not The Translation Text

### ISSUE THREAD

**Issue by AlphaDelta9** [Pokechu22/WorldDownloader#31]
![2016-07-05_19 39 41](https://cloud.githubusercontent.com/assets/6195505/16583463/3dd1d1ca-42e8-11e6-9289-f1dd5d888c06.png)

**Comment by Pokechu22** [comment]
Are you installing via the base edit form or with liteloader?  This would happen if WDL's assets (IE, the translation file) failed to load.

**Comment by AlphaDelta9** [comment]
Use Base Edit, 1.9.4

**Comment by AlphaDelta9** [comment]
I Change The Priority, This Work ^_^
Can Load:
![can load](https://cloud.githubusercontent.com/assets/6195505/16608448/8d5c6ff2-437e-11e6-9aa1-baa46f59f32f.png)
Can't Load:
![cant load](https://cloud.githubusercontent.com/assets/6195505/16608449/8d5e86ca-437e-11e6-882a-2d890eca4f6e.png)

**Comment by AlphaDelta9** [comment]
Can Load, But Crash The Minecraft -_-

**Comment by AlphaDelta9** [comment]
Are This Mod Incompatible With Optifine?

**Comment by Pokechu22** [comment]
When it's installed that way, it can be incompatible but isn't always (if you use the liteloader verison, though, it's completely optifine compatible).  I wouldn't think it would behave like _that_ when used with optifine, though.

You might be able to work around this issue by adding the mod assets as a resource pack - try adding [this](https://github.com/Pokechu22/WorldDownloader/files/349361/1.9_WDL_assets.zip) to your resource packs folder.  No guarantees though; it might not know to load them.

**Comment by AlphaDelta9** [comment]
Nice, Thats Work ;)
Thanks For The Tips :D

**Comment by mmarquezs** [comment]
I also got that but I'm using the liteloader version not the base edit. 
Version 4.0.0.3-1.10.2
Also using Optifine if thats related.

**Comment by afannnn** [comment]
^Same here

**Comment by Pokechu22** [comment]
Hm, will check.  Might be my bug, might be an optifine bug, might be a liteloader bug.

**Comment by uyjulian** [comment]
It's possible the user is selecting a different language, which causes the untranslated strings to be shown.

**Comment by afannnn** [comment]
I have English selected as the language and it is still happening.

**Comment by uyjulian** [comment]
Do you have English (US) selected?

Edit: The language setting is not related to this issue. I just tried to select 日本館 (日本) from the list, and I get English text related to WDL. The language setting will not cause untranslated text to appear.
