### ISSUE TITLE
Download world

### ISSUE THREAD

**Issue by Flameternity** [Pokechu22/WorldDownloader#41]
Can't seem to find the download world option in the escape menu

**Comment by Pokechu22** [comment]
If it's not visible, you've probably installed the mod wrong (for anything newer than a version from several years ago, the button should _always_ be visible in some form, even in single-player).  There's a couple of things that can be done to check (if one of these isn't the case, you've done something wrong with installation; let me know and I can expand upon it):

* Are you on the correct Minecraft launcher profile?
* Is the version in the launcher profile correct?  (Displayed below your name in the launcher)
* For the base edit, what's the text in the top row of F3?  (Minecraft something/something...)
* For the litemod, is there a little tab on the right side of the escape menu that displays a chicken when hovered?

Try redownloading it [from the MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2520465), and follow the instructions again.

**Comment by TypeV** [comment]
For newer versions of the launcher, it automatically downloads and replaces your jar with the vanilla jar, when you load it.

**Comment by Flameternity** [comment]
@Pokechu22 Yep, the launcher and profile are both correct, the base edit text is MultiMC5/vanilla/custom

**Comment by Pokechu22** [comment]
Hm.  That's odd.  You did add the mod in multimc with "Add Jar Mod", and not another mode, right?

**Comment by Flameternity** [comment]
@Pokechu22 yepp

**Comment by Pokechu22** [comment]
Closing this, don't have enough information to answer this and it's been over a year.  If you still need help, please let me know and I'll reopen this.
