### ISSUE TITLE
Compiling custom version for MC 1.10 recompile.sh errors

### ISSUE THREAD

**Issue by grplyler** [Pokechu22/WorldDownloader#43]
Hi,
Im trying to figure out how to compile and custom version of WDL for MC 1.10 (with the WLD `1.10` branch)
Currently i'm using the directions you have provided here for MC 1.7.10 ([https://github.com/Pokechu22/WorldDownloader/issues/27](https://github.com/Pokechu22/WorldDownloader/issues/27))
but i'm running into errors. Specifically these i have put into this gist: [https://gist.github.com/grplyler/32e8cc8967706909adffae0b4c6a8668](https://gist.github.com/grplyler/32e8cc8967706909adffae0b4c6a8668))

I am following the instructions verbatim from issue #27 except when using the `createSymLinks.sh` script. I am using `ln -s $(pwd)/src/wdl $(pwd)/mcp/src/minecraft/wdl` instead of `ln -sr "/src/wdl" "mcp/src/minecraft/wdl"` because `-r1` is not a valid option on OSX.

Not sure it that's causing the issue.

I would just really love to compile a custom version of WDL, and I can't seem to do that with the information I have found so far. If you have any advice or direction on this matter, it would be much appreciated.

And updated procedure for compiling this would would be great. I understand you are working on a better/easier build system. But until then I am willing to do what it takes to compile this mod.

Thanks,
Ryan

**Comment by Pokechu22** [comment]
Hm, I think this is probably a case of the wrong MCP mappings (see #42).  Try [these mappings](http://export.mcpbot.bspk.rs/mcp_snapshot/20160619-1.9.4/mcp_snapshot-20160619-1.9.4.zip) instead (yes, those are 1.9.4 mappings, but I _think_ they're the ones I used at the time).

**Comment by grplyler** [comment]
Yes! That worked. Thank you so much for getting back to me. Would updating the `1.10` branch with the correct mappings fix this problem for other people? If so i can can fork and fix it for ya.

**Comment by Pokechu22** [comment]
It'd fix it probably, but on the other hand, it won't be necessary once I get the build system updated (it'll automatically pick the right mappings since they'll be specified in the build file) :P

**Comment by grplyler** [comment]
Awesome. Now the only thing left on my list to accomplish is when i run `startClient.sh` it gives me a fake player name that I can't use to join any real servers to test out my modifications. Is there anyway to launch the game with `startClient.sh` and the game use my real username and a valid SessionID? Currently im trying to work with [http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1374710-to-modders-auth-yourself-without-a-launcher](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/mods-discussion/1374710-to-modders-auth-yourself-without-a-launcher) but its not been updated to work with 1.10.

**Comment by Pokechu22** [comment]
That's a general MCP side effect - MCP doesn't provide a session token, so the vanilla random name function is used.  I think there's several places to modify it, including passing a JSON file (!?) to `startClient` (I have no clue how that works or even if it still does), directly modifying `Start.java` (probably a good idea since it looks like it's got the wrong asset index too...), or editing `CmdStartClt` in `mcp.cfg` to add the options to the end (that may be the easiest method).  In any case, you'd need to provide the specific arguments as the game excepts them, which you can find by looking at the version's JSON in .minecraft.  For 1.10 what you want is `--username ${auth_player_name} --uuid ${auth_uuid} --accessToken ${auth_access_token}`.

**Comment by grplyler** [comment]
Ok, thanks. I think for now i'll just work on trying to get my custom version working with MultiMC. Thanks.
