### ISSUE TITLE
Creating zip of reobfuscated files for use with MultiMC

### ISSUE THREAD

**Issue by grplyler** [Pokechu22/WorldDownloader#44]
I have gotten a custom version of WDL to compile but it has no `assets` folder like the official mod releases do. I thought this would be as simple as copying the assets folder in there and then zipping the reobfs/minecraft folder to make "jar mod" i can install with MultiMC.

But when I do this, there is no "Download this world" button in the games GUI.

Is this a matter of the assets not being properly supplied to the build? If so, how do i connect the assets to the build. Or is there something else
to installing a custom build of WDL other than zipping up the contents of `reobfs/minecraft/*`

Thank you for your assistance,
Ryan

**Comment by Pokechu22** [comment]
MCP doesn't always copy the assets over.  You may need to manually copy the assets into the folder you've created.  However, even if assets didn't copy, there should be a button on the GUI (though without the assets the button text would be wrong).

Zip folders can be a bit tricky - make sure that if you open the zip folder you created, there isn't a `minecraft` folder inside of it but instead just the classes.  If you open the reobfs/minecraft folder, select all, and _then_ zip it should produce the right kind of zip folder.

**Comment by grplyler** [comment]
That worked. Thank you so much for your timely response. I was selecting the `reobfs/minecraft` folder and zipping. I instead selected all its contents and then zipped. This created it properly and if working swell with MultiMC.

:)
