### ISSUE TITLE
Overriding game rules

### ISSUE THREAD

**Issue by VeganMars** [Pokechu22/WorldDownloader#47]
I am not sure how this should be handled but I think it would be really awesome if there would be a way to easily set further world configurations, specfically disable fire spread (and block destruction) and ice melt. Of course I can run ASAP after joining in my local world for the first time:

    /gamerule fireSpread false           ; Disables fire spread.
    /gamerule doFireTick false           ; Prevents block destructive. (It appears this already suffices but I haven't tested all possible scenarios.)

For ice melting it is a bit more complicated and only `/gamerule randomTickSpeed 0` would do the trick but it would also stop

* plants from growing
* fire and grass from spreading
* tilled soil from turning back into dirt.
(source: https://www.quora.com/Is-there-a-way-to-stop-ice-melting-in-Minecraft-with-no-mods)

Maybe there could be an option to "freeze" the world so you can inspect it after a download without worrying about any harm occuring to the world. I am looking forward to an opinion if such a feature would be acceptable?

**Comment by Pokechu22** [comment]
I know that soccerguy3 has a "Fire and Ice" mod that simply stops fire and ice from freezing; you could use that.

Another option would be that I can add a GUI to customize game rules in the downloaded world - that probably wouldn't be too hard to make (the same customization is already done with things like player position, enabling cheats, changing the generator, etc).

**Comment by VeganMars** [comment]
Ok I guess this issue can go on the "nice to have but not really a requirement feature request list".

I guess the Fire and Ice mod might get the job done (altough there doesn't seem to be a lightloader version). And as I stated the above game rule trick should also do it without any mod. (What I will try out tomorrow is check if these settings are preserved after a second write to the downloaded world.)

**Comment by Tsoccerguy3** [comment]
Global Game Rules
This feature has been already implemented in this mod and includes all the rules
https://mods.curse.com/mc-mods/minecraft/227657-global-gamerules#comments

WorldHandler
Game Rules plus so much more
https://minecraft.curseforge.com/projects/world-handler-command-gui

Use these for Single or multiplayer map protection . There are now more options than these mods for protecting a map

**Comment by Pokechu22** [comment]
This was implemented a few versions ago.
