### ISSUE TITLE
Github File Download Not Working

### ISSUE THREAD

**Issue by yamidcheese** [Pokechu22/WorldDownloader#51]
Although the links to download the files on the Minecraft Forums work, none of the github downloads for either Version 4.0.0.1 or Version 4.0.0.0 work. Only the source code downloads work.

**Comment by Pokechu22** [comment]
Can confirm, downloads seem to be broken.

However, it looks like it is an issue on Github's end; [their status site](https://status.github.com/) states:

> **10:00 Pacific Standard Time** We are investigating issues serving web hooks as well as assets on GitHub.com. 

I'm probably not able to fix this; it's an issue on GitHub's end.  Hopefully it'll be fixed shortly, though.

**Comment by yamidcheese** [comment]
Could you not put up an alternative download link on the minecraft forums?

**Comment by Pokechu22** [comment]
No, I'm not at my home computer and don't have access to the forums (or the compiled files).  Otherwise, I would put up a temporary download.  Sorry :/

There _was_ a status update:

> **11:32 Pacific Standard Time** Webhooks are now delivering normally but webhook logs will be delayed. We are continuing to monitor other assets recovery.

**Comment by Pokechu22** [comment]
The files seem to currently be accessible.  I can't say for sure whether it's stable or not, though.  I'll close this issue once GitHub marks the problem as resolved on their status site.

**Comment by Pokechu22** [comment]
> **20:37 Pacific Standard Time** Everything operating normally. 

(8:37 PM PST) Everything is back to normal.  I'm going to close the issue for now, but I will look into a second host (it's _probably_ not worth it because a bunch of sites went down due to S3 going down, not just GH itself &mdash; even Minecraft itself had issues &mdash; but I might find something that I can use).
