### ISSUE TITLE
Errors in build.gradle

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#53]
error online 25
change from 
classpath 'pokechu22.test.begradle:begradle:0.0.2-snapshot
to
classpath 'pokechu22.test.begradle:begradle:0.0.3

16 compile errors

`#################################################
         ForgeGradle 0.0.3-2c94033
  https://github.com/MinecraftForge/ForgeGradle
#################################################
               Powered by MCP unknown
             http://modcoderpack.com
         by: Searge, ProfMobius, Fesh0r,
         R4wk, ZeuX, IngisKahn, bspkrs
#################################################
This mapping 'snapshot_20170301' was designed for MC 1.11! Use at your own peril.
:1.10.2:deobfCompileDummyTask
:1.10.2:deobfProvidedDummyTask
:1.10.2:getVersionJson
:1.10.2:downloadClient SKIPPED
:1.10.2:extractDependencyATs SKIPPED
:1.10.2:extractMcpData SKIPPED
:1.10.2:extractMcpMappings
Download http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot/20170301-1.11/mcp_snapshot-20170301-1.11.zip
:1.10.2:genSrgs
:1.10.2:deobfMcSRG SKIPPED
:1.10.2:decompileMc SKIPPED
:1.10.2:fixMcSources SKIPPED
:1.10.2:remapMcSources SKIPPED
:1.10.2:processApiBasePatches SKIPPED
:1.10.2:sourceApiJava
:1.10.2:compileApiJava UP-TO-DATE
:1.10.2:processApiResources UP-TO-DATE
:1.10.2:apiClasses UP-TO-DATE
:1.10.2:processBasePatches
Generating patch for net.minecraft.client.gui.GuiIngameMenu from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\client\gui\GuiIngameMenu.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.client.gui.GuiIngameMenu.patch
Generating patch for net.minecraft.client.multiplayer.WorldClient from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\client\multiplayer\WorldClient.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.client.multiplayer.WorldClient.patch
Generating patch for net.minecraft.client.network.NetHandlerPlayClient from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\client\network\NetHandlerPlayClient.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.client.network.NetHandlerPlayClient.patch
Generating patch for net.minecraft.crash.CrashReport from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\crash\CrashReport.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.crash.CrashReport.patch
Generating patch for net.minecraft.client.ClientBrandRetriever from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\client\ClientBrandRetriever.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.client.ClientBrandRetriever.patch
Generating patch for net.minecraft.client.resources.DefaultResourcePack from C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base\net\minecraft\client\resources\DefaultResourcePack.java to C:\Users\ASUS\Dev\wdl4\1.10.2\src\main\base-patches\net.minecraft.client.resources.DefaultResourcePack.patch
:1.10.2:sourceMainJava
:1.10.2:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:1.10.2:processResources
:1.10.2:classes
:1.10.2:jar
:1.10.2:processTestBasePatches SKIPPED
:1.10.2:sourceTestJava
:1.10.2:compileTestJava UP-TO-DATE
:1.10.2:processTestResources UP-TO-DATE
:1.10.2:testClasses UP-TO-DATE
:1.10.2:test UP-TO-DATE
:1.10.2:reobfJar
:1.10.2:extractRangemapReplacedMain
C:\Users\ASUS\Dev\wdl4\1.10.2\build\sources\main\java
:1.10.2:retromapReplacedMain
remapping source...
:1.10.2:sourceJar
:1.10.2:assemble
:1.10.2:check UP-TO-DATE
:1.10.2:build
:1.11:deobfCompileDummyTask
:1.11:deobfProvidedDummyTask
:1.11:getVersionJson
:1.11:downloadClient SKIPPED
:1.11:extractDependencyATs SKIPPED
:1.11:extractMcpData SKIPPED
:1.11:extractMcpMappings SKIPPED
:1.11:genSrgs
:1.11:deobfMcSRG SKIPPED
:1.11:decompileMc SKIPPED
:1.11:fixMcSources
:1.11:remapMcSources SKIPPED
:1.11:processApiBasePatches SKIPPED
:1.11:sourceApiJava
:1.11:compileApiJava UP-TO-DATE
:1.11:processApiResources UP-TO-DATE
:1.11:apiClasses UP-TO-DATE
:1.11:processBasePatches
Generating patch for net.minecraft.client.gui.GuiIngameMenu from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\client\gui\GuiIngameMenu.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.client.gui.GuiIngameMenu.patch
Generating patch for net.minecraft.client.multiplayer.WorldClient from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\client\multiplayer\WorldClient.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.client.multiplayer.WorldClient.patch
Generating patch for net.minecraft.client.network.NetHandlerPlayClient from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\client\network\NetHandlerPlayClient.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.client.network.NetHandlerPlayClient.patch
Generating patch for net.minecraft.crash.CrashReport from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\crash\CrashReport.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.crash.CrashReport.patch
Generating patch for net.minecraft.client.ClientBrandRetriever from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\client\ClientBrandRetriever.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.client.ClientBrandRetriever.patch
Generating patch for net.minecraft.client.resources.DefaultResourcePack from C:\Users\ASUS\Dev\wdl4\1.11\src\main\base\net\minecraft\client\resources\DefaultResourcePack.java to C:\Users\ASUS\Dev\wdl4\1.11\src\main\base-patches\net.minecraft.client.resources.DefaultResourcePack.patch
:1.11:sourceMainJava
:1.11:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:89: error: cannot find symbol
import net.minecraft.entity.passive.AbstractHorse;
                                   ^
  symbol:   class AbstractHorse
  location: package net.minecraft.entity.passive
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\gui\GuiIngameMenu.java:101: error: cannot find symbol
                this.drawCenteredString(this.fontRendererObj, I18n.format("menu.game", new Object[0]), this.width / 2, 40, 16777215);
                                            ^
  symbol: variable fontRendererObj
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:85: error: cannot find symbol
                this.theProfiler.startSection("reEntryProcessing");
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:96: error: cannot find symbol
                this.theProfiler.endStartSection("chunkCache");
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:98: error: cannot find symbol
                this.theProfiler.endStartSection("blocks");
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:100: error: cannot find symbol
                this.theProfiler.endSection();
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:129: error: cannot find symbol
                this.theProfiler.startSection("buildList");
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:139: error: cannot find symbol
                this.theProfiler.endSection();
                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:161: error: cannot find symbol
                                this.theProfiler.startSection("getChunk");
                                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\multiplayer\WorldClient.java:164: error: cannot find symbol
                                this.theProfiler.endSection();
                                    ^
  symbol: variable theProfiler
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1007: error: cannot find symbol
                        if (entity instanceof AbstractHorse) {
                                              ^
  symbol:   class AbstractHorse
  location: class NetHandlerPlayClient
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1008: error: cannot find symbol
                                entityplayersp.openGuiHorseInventory((AbstractHorse)entity, new ContainerHorseChest(packetIn.getWindowTitle(), packetIn.getSlotCount()));
                                                                      ^
  symbol:   class AbstractHorse
  location: class NetHandlerPlayClient
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1718: error: cannot find symbol
                        scoreplayerteam.setTeamName(packetIn.getDisplayName());
                                       ^
  symbol:   method setTeamName(String)
  location: variable scoreplayerteam of type ScorePlayerTeam
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1719: error: cannot find symbol
                        scoreplayerteam.setNamePrefix(packetIn.getPrefix());
                                       ^
  symbol:   method setNamePrefix(String)
  location: variable scoreplayerteam of type ScorePlayerTeam
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1720: error: cannot find symbol
                        scoreplayerteam.setNameSuffix(packetIn.getSuffix());
                                       ^
  symbol:   method setNameSuffix(String)
  location: variable scoreplayerteam of type ScorePlayerTeam
C:\Users\ASUS\Dev\wdl4\1.11\build\sources\main\java\net\minecraft\client\network\NetHandlerPlayClient.java:1721: error: cannot find symbol
                        scoreplayerteam.setChatFormat(TextFormatting.fromColorIndex(packetIn.getColor()));
                                       ^
  symbol:   method setChatFormat(TextFormatting)
  location: variable scoreplayerteam of type ScorePlayerTeam
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
16 errors
1 warning
:1.11:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':1.11:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 39.381 secs
----------------------------------------
Compilation failed.
If this was due to a bad class file, try running "gradlew setupDecompWorkspace"
The cause of this behavior is being investigated.`

**Comment by Pokechu22** [comment]
Fixed, I think.  I believe those compile errors will go away once you update begradle.  If not, feel free to reopen.
