### ISSUE TITLE
[Question] [1.8.9] Regarding onWorldLoad 

### ISSUE THREAD

**Issue by boomboompower** [Pokechu22/WorldDownloader#54]
With the following method, you send a request prefixed with WDL|

Taken from ( https://github.com/Pokechu22/WorldDownloader/blob/1.8.9a/src/wdl/WDLPluginChannels.java#L598-L638 )

        static void onWorldLoad() {
		Minecraft minecraft = Minecraft.getMinecraft();
		
		receivedPackets = new HashSet<Integer>();
		requests = new HashMap<String, String>();
		chunkOverrideRequests = new ArrayList<ChunkRange>();
		
		canUseFunctionsUnknownToServer = true;
		
		WDLMessages.chatMessageTranslated(
				WDLMessageTypes.PLUGIN_CHANNEL_MESSAGE,
				"wdl.messages.permissions.init");
		
		// Register the WDL messages.
		PacketBuffer registerPacketBuffer = new PacketBuffer(Unpooled.buffer());
		// Done like this because "buffer.writeString" doesn't do the propper
		// null-terminated strings.
		registerPacketBuffer.writeBytes(new byte[] {
				'W', 'D', 'L', '|', 'I', 'N', 'I', 'T', '\0',
				'W', 'D', 'L', '|', 'C', 'O', 'N', 'T', 'R', 'O', 'L', '\0',
				'W', 'D', 'L', '|', 'R', 'E', 'Q', 'U', 'E', 'S', 'T', '\0' });
		C17PacketCustomPayload registerPacket = new C17PacketCustomPayload(
				"REGISTER", registerPacketBuffer);
		minecraft.getNetHandler().addToSendQueue(registerPacket);

		// Send the init message.
		C17PacketCustomPayload initPacket;
		try {
			initPacket = new C17PacketCustomPayload("WDL|INIT",
					new PacketBuffer(Unpooled.copiedBuffer(WDL.VERSION
							.getBytes("UTF-8"))));
		} catch (UnsupportedEncodingException e) {
			WDLMessages.chatMessageTranslated(WDLMessageTypes.ERROR,
					"wdl.messages.generalError.noUTF8", e);

			initPacket = new C17PacketCustomPayload("WDL|INIT",
					new PacketBuffer(Unpooled.buffer()));
		}
		minecraft.getNetHandler().addToSendQueue(initPacket);
	}

Would it matter if the payload did not contain WDL? Am talking about `WDL|INIT`, `WDL|CONTROL` and `WDL|REQUEST`

**Comment by Pokechu22** [comment]
For more info about those channels, look at the [wiki.vg article](http://wiki.vg/Plugin_channels/World_downloader).  The channel name shouldn't be changed now since it's already specified; it's like the [`MC|` channels](http://wiki.vg/Plugin_channels) used in vanilla.

**Comment by Pokechu22** [comment]
Closing, issue is 1 year old and adequately answered.
