### ISSUE TITLE
Solution for Anti-WorldDownloader?

### ISSUE THREAD

**Issue by Gtronos** [Pokechu22/WorldDownloader#55]
Is there any solution for the Anti-WorldDownloader?
Without asking the server owner to disable this plugin or a bypass permission?

Thanks.

**Comment by Pokechu22** [comment]
Context-sensitive.  Under special situations, yes, but I still encourage trying to achieve a consensus with the server owner (the system that those plugins hijack was designed to allow permission _requests_, not _denials_).

This is handled on a case-by-case basis, privately - [PM me on the forums](http://www.minecraftforum.net/private-messages/send?recipient=Pokechu22) for more information.  If you have a valid case, I can help.

**Comment by Eyremba** [comment]
Just recode the mod so that it does not send to the server that it is "WorldDownloader".

That's done in 3 minutes if you know how.
