### ISSUE TITLE
World_BYpass

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [Pokechu22/WorldDownloader#57]
how to bypass server protection as some servers full on lock you out of it so cant back up your own builds

**Comment by uyjulian** [comment]
Ask the server owner to give you permission to back up your own builds.

If you are being kicked out of the server with this mod installed, private message "Pokechu22" or "soccerguy3" on minecraftforums.net for assistance.

**Comment by Eyremba** [comment]
Just recode the mod so that it does not send to the server that it is "WorldDownloader".

That's done in 3 minutes if you know how.

**Comment by TWIISTED-STUDIOS** [comment]
how would one go about doing that eyremba would you care to help please

**Comment by Pokechu22** [comment]
Please [PM me on the forums](http://www.minecraftforum.net/private-messages/send?recipient=Pokechu22).

**Comment by TWIISTED-STUDIOS** [comment]
sent

**Comment by uyjulian** [comment]
I'll close this issue.
