### ISSUE TITLE
BeGradle version do not match

### ISSUE THREAD

**Issue by roro1506HD** [Pokechu22/WorldDownloader#60]
Hello, as I want to change a little thing for my own, I've downloaded this repo and begradle's one. But when I use the begradle "gradlew build" it builds the version 0.0.4, and WorldDownloader required BeGradle 0.1.0

Edit : I'm using the v4 branch

2nd Edit : I just found that every version was handled by the current version of begradle except 1.12, this one is handled by begradle 0.1.0 which is not on the begradle's repo.

(It could just be me, I'm not really smart)

**Comment by Pokechu22** [comment]
Ooops...  Right, I forgot to push that.

Right now, WDL requires both begradle 0.0.4 ([7478651](https://github.com/Pokechu22/ForgeGradle-extensions/tree/74786519400cfdffb199fde6fec053c8763fbc92)), and begradle 0.1.0 ([358b578](https://github.com/Pokechu22/ForgeGradle-extensions/tree/358b578775ee5af609727b14d6c530bbb7abd3fa)).  It's messy, and that's one of the problems I've run into recently trying to get everything to work with 1.12 (FG 2.3 and FG 2.2 only work for 1.12 and non-1.12 versions, respectively).

**Comment by roro1506HD** [comment]
Thanks a lot man, now I can compile :) Yesterday I had my game crashing when I was touching a button, I didn't knew for what reason. I switch to the latest build (this morning) and it worked. Thanks for the fix ^^
