### ISSUE TITLE
Chests/Dispensers/... items not saved on ModulMonde

### ISSUE THREAD

**Issue by d-faure** [Pokechu22/WorldDownloader#66]
The server is 1.12.1 derived from Spigot and located at: play.modulmonde.com

**Comment by Pokechu22** [comment]
Are you opening the containers?  You need to open them (while downloading) to save them, and should get a message in chat when you do so.  If nothing's appearing in chat, that's odd.

**Comment by d-faure** [comment]
All containers have been opened / checked with a related message in chat
log, but nothing found when opening them in the saved game.

**Comment by Pokechu22** [comment]
Can you upload the log file from %appdata%\.minecraft\logs? (it'll be `latest.log` if you haven't started the game since then, otherwise it'll be one of the compressed log files)

**Comment by d-faure** [comment]
Here's a simple session, overwriting previous download and opening few chests:

[latest.log.txt](https://github.com/Pokechu22/WorldDownloader/files/1271518/latest.log.txt)

**Comment by Pokechu22** [comment]
Huh.  Yea, that looks reasonable.  I also see the saving message:

```
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Utilisation nouveau TE: minecraft:chest (avl) à et{x=-3504, y=64, z=-6541}
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Utilisation nouveau TE: minecraft:chest (avl) à et{x=-3504, y=64, z=-6540}
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Utilisation nouveau TE: minecraft:chest (avl) à et{x=-3504, y=63, z=-6541}
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Utilisation nouveau TE: minecraft:chest (avl) à et{x=-3504, y=63, z=-6540}
```

(written only in the log, not in chat, since that message is disabled by default).

By all accounts, it _should_ have been written, but it wasn't... that's very mysterious.

Though actually, I have a guess at what might be happening.  It might be that WDL's using the wrong type ID for the block entities (but if that's the case, why hasn't it caused problems before?)

Can you upload the zipped copy of the world that WDL automatically saves?  It should have all block entities in it, as they existed before loading.

**Comment by Pokechu22** [comment]
Tested on a local test server (running spigot), and I can't reproduce this issue.  I can reproduce the issue when importing block entities, though.

And actually:

```
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Utilisation nouveau TE: minecraft:chest (avl) à et{x=-3504, y=61, z=-6553}
```

is later followed by:

```
[22:57:04] [WDL Save Thread/INFO]: [WorldDL] Ancien TE n'a pas besoin d'import: minecraft:chest à et{x=-3504, y=61, z=-6553} 
```

so that implies that the same chunk's being imported later and the block entity isn't saved.

**Comment by d-faure** [comment]
That's it! Lastly, as I was preparing a not-too-big map area backup, I
found that initial saving was getting the items as expected. Then, as I
checked the (re)generated map once retrieved more stuff in another session
on the same backup, my chests appeared empty.
Is it a backup merging issue?

**Comment by Pokechu22** [comment]
Yea - the block entity importing process is the one that keeps block entities from the last time the map was downloaded.

Should have a fix soon.

**Comment by Pokechu22** [comment]
OK, try [version 4.0.1.1](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.1.1), which should hopefully fix the problem.

**Comment by d-faure** [comment]
I just re- checked and it works now. Thanks.

**Comment by Pokechu22** [comment]
Alright, glad to help!
