### ISSUE TITLE
Error on 4.0.1.7 - Crash on disconnect

### ISSUE THREAD

**Issue by shmith** [Pokechu22/WorldDownloader#72]
There is an error in 4.0.1.7 were when I disconnect from the server while the world is downloading my game crashes. I remember distinctly that the world should save then disconnect but I get a big error and my game crashes. This is annoying as I often forget to stop the download before I disconnect. 

Link to crash report: **https://pastebin.com/fZiiwt4k**

**Comment by Pokechu22** [comment]
Thanks for the report.  The mod's supposed to automatically stop downloading when you disconnect, but it looks like some stuff is going wrong during that process (or rather with the save progress screen).

It too remember that it's supposed to save and disconnect ideally, but I haven't actually tested that in a while (and it might be that forge behaves differently).

**Comment by xTachyon** [comment]
I can confirm this is happening. Here is the crash log on my machine: https://gist.github.com/xTachyon/a79ad3fadd0352587673bfc11c49edda

**Comment by Pokechu22** [comment]
I've pushed a commit that stops the crash.  Clearly, [everything is fine now](https://user-images.githubusercontent.com/8334194/35199077-95ed2e84-fef0-11e7-83d7-bd6088169c84.png).

More seriously, it'll take a fair bit of work to get this to behave right, but this is a start at least...

**Comment by shmith** [comment]
@Pokechu22 Am I able to get a base edit with this issue fixed or do I have to wait for the next release?

**Comment by Pokechu22** [comment]
You'll have to wait for the next release unless you're willing to compile it for yourself.  There's a few other things that I'm in the middle of that make me not want to do release just yet.

**Comment by minexew** [comment]
FWIW, I'm also getting this error on 4.0.1.7.

**Comment by Pokechu22** [comment]
I've released [version 4.0.2.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.2.0) which should fix this issue.  Please let me know if it's still happening after updating.

**Comment by VADemon** [comment]
Quick heads up: solid 17h non-stop download across 3 clients, no crashes. Running 4.0.3.1. Other guys who use the affected version frequently crash.

**Comment by Pokechu22** [comment]
Well, if you're running a version where the bug is fixed (any one greater than 4.0.2.0), I'd expect it to not have the bug anymore :P  Why haven't the other people updated?  There've been newer versions for over half a year...
