### ISSUE TITLE
WDL causes a mommentary freeze while flying 

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#74]
There is a repeating momentary freeze , that is noticeable while flying . This has been a bug in past builds but was fixed . It's back in the latest code that I compiled . Putting up Windows 10 Task Manager Performance screen I can see Drops in CPU and WIFI at WDL freezes . Not Present when WDL is off

**Comment by Pokechu22** [comment]
Are you downloading at the time?

It's probably when you're unloading chunks, and then those chunks are being saved as you move; there's a bit of a spike as all of the unloaded chunks are saved at once.  This might be avoidable, but it's a bit difficult.

Though if it didn't happen in past builds, that's weird.

**Comment by Tsoccerguy3** [comment]
Yes this only occurs while downloading . I remember this bug from way back . I'm using the liteloader version . This shouldn't happen , everything is running on a intel i7 7700k 16 gigs ram with a 512 SSD

**Comment by Pokechu22** [comment]
You say it was fixed before; can you test some older versions and see if it also happens with those?  I don't remember doing anything to specifically fix this.

That said, this is something that I'd like to look into for the update after the next, as I'll already be investigating the rest of the save process.

**Comment by jascotty2** [comment]
This does not seem to be directly caused by the WDL mod, but is certainly amplified by it.
Minecraft with LiteLoader gets bigger and bigger the more chunks that are loaded, and memory dumps show hundreds of thousands of HashMaps with 0 or 1 values. Those with an entry have an ArrayList, which may also have 0 or 1 values.

I have reproducibly been able to get this to happen much faster by traveling (loading more chunks) and even faster still if running the WDL mod, and faster with downloading enabled.

I'm not sure what's the cause right now, but it does not seem to be restricted to WDL

**Comment by jascotty2** [comment]
[rescinding prior comment about LiteLoader]

The memory that GC cannot free gets bigger and bigger with more chunks that are loaded over time, and memory dumps show hundreds of thousands of HashMaps with 0 or 1 values. Those with an entry have an ArrayList, which may also have 0 or 1 values.

I have reproducibly been able to get this to happen much faster by traveling (loading more chunks) and even faster still if downloading is enabled.

I'm not sure what's the cause right now, but it does seem related to the number of chunks that have been loaded while playing the game

**Comment by Pokechu22** [comment]
I'm not sure about the dumps specifically, but I will note that WDL keeps some information even after chunks have unloaded (to help with importing things):

https://github.com/Pokechu22/WorldDownloader/blob/6f8c59c2bdc291173d00d264ecae1a35633a4c61/share/src/main/java/wdl/WDL.java#L153-L161

These are only emptied in `startDownloading`, which is definitely not ideal as they're not used after saving stops.

Though, I'm not fully sure these map the description.  One is a `HashMultimap`, and I'm not entirely sure about the implementation for that (but I don't think it uses an `ArrayList`).  Also, I'd expect it to have more than 1 value in some cases...  Can you tell for sure that it's in WDL code?  Or is it possibly in vanilla?

Also, have you attempted to reproduce this bug in vanilla (i.e. without WDL or liteloader installed)?  If so I'll still look into it, but in the end it'd make sense to post the final results on bugs.mojang.com instead.

**Comment by jascotty2** [comment]
I tried with WDL not loaded, and did not find the same issues.

I also found that there were two separate bits that needed tweaks to fix this - the references to mcProfiler were also causing excessive HashMaps to be linked and protected from GC.

Compiled into Pull#77

Does not seem to completely resolve the momentary freeze, but does keep the client working if running for a long time

**Comment by Tsoccerguy3** [comment]
Jascotty , I compiled a build with your pull request , the stutter is barely noticeable , but entities don't get saved .
things like frame map contents and statues . maybe more . 

Well actually statues were not getting saved before i added your fixes so , I can just say the map data was lost

**Comment by Tsoccerguy3** [comment]
I updated PC to Windows 10 x64 RS4 , RTM final being pushed to Fast Ring this week.  Stutter is gone , Pc is smooth and stable . WDL working well . except it  misses some random things and i don't know why . I think this problem was windows or driver related . It's still a good thing to optimize the WDL code . I'm closing this for now .
