### ISSUE TITLE
When building for 1.11 or 1.11.2, builds for 1.10 instead

### ISSUE THREAD

**Issue by jascotty2** [Pokechu22/WorldDownloader#75]
Trying to tinker with the mod, and the other versions I've tried all work, but for whatever reason 1.11-litemod and 1.11.2-litemod both compile for 1.10 instead of their respective versions

Any idea what might be going on?

Side note: each version invariably fails build until you manually create a directory for 
'/WorldDownloader-4/<version>/src/main/base'
just the major builds, though - not the litemod builds

**Comment by jascotty2** [comment]
Notes to reproduce:

Fresh download of source from github repository
Fresh download of BEGradle
Extract and run from BEGradle directory: ./gradlew install
Extract WorldDownloader
(commented out 1.9 projects from build.gradle and settings.gradle)
Run within the WorldDownloader folder:
./gradlew setupDecompWorkspace
./gradlew build

**Comment by Pokechu22** [comment]
Hm.  As in, it generates a binary for 1.10 in the `libs` folder?  Is the generated file named after 1.10, or instead does it only work with 1.10 even though it claims to be for another version?

> Side note: each version invariably fails build until you manually create a directory for
 '/WorldDownloader-4//src/main/base'

Thanks for reporting that, will fix (should be easy to do).

**Comment by jascotty2** [comment]
1.11 litemod.json:
{
    "name": "LitemodStub",
    "mcversion": "1.10",
    "mixinConfigs": [
        "mixins.LiteModWDL.json"
    ]
}

Additionally, modifying this file to make liteloader attempt to load the file causes the game to crash

**Comment by Pokechu22** [comment]
Ah, you're right.

Fortunately that file is replaced by an auto-generated one in the actual build process, but that will cause issues in the IDE.  Fixing...

**Comment by Pokechu22** [comment]
Both issues should now be fixed (you'll need to pull and rebuild begradle).  Can you confirm that they're fixed for me?

**Comment by jascotty2** [comment]
1.11 and 1.11.2 load correctly now :)
