### ISSUE TITLE
Some double chests only save top half of items

### ISSUE THREAD

**Issue by gourdo1** [Pokechu22/WorldDownloader#8]
With 1.8b, I noticed that certain double chests are only saving the top half of the items in that chest.

**Comment by Pokechu22** [comment]
Is this in a set of double-chests and trapped double chests right next to eachother, with the chests facing east or west?  If so, I think I know the cause.

**Comment by Pokechu22** [comment]
Actually, can you take a screenshot with F3 open while looking at the chests that caused this issue?

**Comment by gourdo1** [comment]
May not get to this for a few days as I'm out of town... You may be right about this one. I'll try to find some time to get this reproducible. Thanks for taking this on so quickly.
