### ISSUE TITLE
AntiWDL

### ISSUE THREAD

**Issue by HeraKieuAnh** [Pokechu22/WorldDownloader#80]
How to overcome AntiWDL and not kicked out of the server

**Comment by Eyremba** [comment]
> How to overcome AntiWDL and not kicked out of the server

Remove the shitty plugin channel stuff, then the server won't know that you are using the mod.

**Comment by Pokechu22** [comment]
Please [send me a PM](https://www.minecraftforum.net/private-messages/send?recipient=pokechu22).  Those plugins work by hijacking the [plugin message functionality](http://wiki.vg/Plugin_channels/World_downloader) in the mod, which is _supposed_ to provide a fair and balanced way of restricting use while still allowing players to provide a way to get permission when they need it.  I can override it for you, if you have a valid case, but each one of these cases is individual so I prefer handling it via PMs.
