### ISSUE TITLE
Mod installed via MultiMC, no "download world" button in server

### ISSUE THREAD

**Issue by Straighten-Your-Back** [Pokechu22/WorldDownloader#81]
Used MultiMC to download the relevent version (for 1.12.2), the mod is installed both as a zip and unzipped folder (because zip didn't work, so I tried unzipping just to see....obviously not), removing one doesn't allow the other to function.

No other mods in use.

Since there are no actual instructions on the MultiMC website explaining how to use it, and no instructions for this mod explaining how to use it, I have no idea if this is an issue or if I'm just not doing what I'm supposed to because there's no way for me to know what I'm supposed to do.

**Comment by Pokechu22** [comment]
When using MultiMC, you'll need to use the "add jar mod" function, not the regular mod button (that's the one for forge mods).  Does that solve the issue?

**Comment by Straighten-Your-Back** [comment]
Forgot my password to this account so it took me a while to get back, but yes, that did resolve the issue. Thank you.

**Comment by Pokechu22** [comment]
Alright, glad that solved it.
