### ISSUE TITLE
No source for WDL 1.12/1.12.2?

### ISSUE THREAD

**Issue by D3SOX** [Pokechu22/WorldDownloader#83]
Hi,

I can't find the sources for WDL for 1.12 or 1.12.2.
Like this https://github.com/Pokechu22/WorldDownloader/tree/1.11a-beta1

Regards

**Comment by Pokechu22** [comment]
Everything's on the `v4` branch (for all MC versions that I'm supporting, i.e. 1.9+); I've switched away from the version-per-branch system since I'm no longer directly using MCP.  For 1.12.2, source is in the `1.12.2` folder _and_ the `share` folder.

**Comment by D3SOX** [comment]
Thanks, can be closed.
