### ISSUE TITLE
Latest compile the save GUI now offers up the name 3 times for all maps 

### ISSUE THREAD

**Issue by Tsoccerguy3** [Pokechu22/WorldDownloader#85]
![2018-07-19_07 31 45](https://user-images.githubusercontent.com/22108822/42940213-a4c48d4a-8b26-11e8-8023-bf19b128163c.png)
![2018-07-19_07 31 51](https://user-images.githubusercontent.com/22108822/42940214-a4d469a4-8b26-11e8-830a-51c2135894b4.png)
![2018-07-19_07 31 53](https://user-images.githubusercontent.com/22108822/42940216-a4e1c572-8b26-11e8-8aa2-cd72722ad1c6.png)

3 times the charm , everything 3

**Comment by Pokechu22** [comment]
This is interesting, and I noticed something similar... if you select "copy debug info" it'll list everything in base properties thrice too...  No idea why it's doing that just yet, but I'd assume the two are related.

**Comment by Pokechu22** [comment]
Fixed.  The copy debug info thing was unrelated (ddec4239870f1624a9b3f7f5cb899702f224d1e8, just a typo); the issue was that I was still using the `id` field to select the world but stopped assigning it.
