### ISSUE TITLE
Can you help me?  (Unable to download due to custom pause menu not having the same buttons)

### ISSUE THREAD

**Issue by leopoldhub** [Pokechu22/WorldDownloader#86]
hello, first of all, im french so my english is pretty bad... sorry ^^.
Recently, i build a 15X15 chunk's monument on a moded minecraft serveur and, to save it, i ask to the admins if they can give me my build and they said "you can take it but do it yourself", so i download WDL in 1.7.10 and i try it without mods and its working but in the launcher, the buttons **don't appear** because the modpack **edit the pause menu...**
So, I asked myself if it is possible to you to made an **addon** for the mod to add **shortcuts keys** (to **simulate the buttons clicking**).
Thx ^^

**Comment by Pokechu22** [comment]
1.7.10, that's pretty old...  I haven't messed with it in a while.  I'm currently unavailable but I can try to look into this later today.

There are some things to check first, though, to make sure the mod was correctly installed.

* If you got a notice in chat about it, then it was; in that case it's definitely a button issue.
* Check if there is a little tab on the top right of the main menu, which when hovered shows a chicken.  If it isn't present, liteloader was installed wrong.
* Click the aforementioned tab.  Is WDL in the list of loaded mods?  If not you installed liteloader but not WDL - make sure to put the litemod in the .minecraft/mods folder, with the file extension lotemod; don't use the base edit as it is incompatible.

If it definitely is a button issue, you can also try temporarily disabling the mod that changes the menu; if it's voxelmenu this should be possible from the liteloader menu.

**Comment by leopoldhub** [comment]
@Pokechu22 WDL and liteloader are correctly installed and its a problem with an other forge mod who modify the pause menu. i try to disable the problematic mod and its working but its the main mod of the launcher and i cant be connected on the server if i disable it...
thx for your quick reply ^^. (it would be really good if it was possible ^^)

**Comment by Pokechu22** [comment]
I've written up a forge mod that binds <kbd>K</kbd> and <kbd>L</kbd> to start/stop downloading: 
[WDL-Keybinding.zip](https://github.com/Pokechu22/WorldDownloader/files/2226415/WDL-Keybinding.zip) (source is also in there).  Hopefully this works; I haven't done much stuff with forge and definitely not with 1.7.10 (I would have done a litemod, but I couldn't find any info on how to use liteloader with forgegradle back then, and didn't want to do some awful MCP-based setup).  I did some minimal testing and everything seemed fine though.  If there are any issues, let me know and I'll try to fix it.

**Comment by uyjulian** [comment]
@Pokechu22 Liteloader for 1.7.10 uses the old Ant+MCP setup. There is no ForgeGradle buildsystem for Liteloader 1.7.10.

**Comment by leopoldhub** [comment]
@Pokechu22 mhh... its not working... 

Crash report:
 https://pastebin.com/XAeSBxeP

  I don' know why... (i use mod_WorldDownloader_8d05de448a5d76e4ec3acb325b8f641166fa158d_mc1.7.10(litemod) and forge 10.13.4.1614 and liteloader 1.7.10_04). maybe it is because i use a litemod version of liteloader (i dont know if there is a forge version for 1.7.10) i try to launch minecraft with only wdl-keybinding-1.0.jar and its not working...

**Comment by leopoldhub** [comment]
and, when i try to launch minecraft with the basedit version of wdl with forge i cant go in singleplayer or multiplayer because the game crash... (Im obliged to use the litemod version...)

**Comment by Pokechu22** [comment]
Ah, dang, I think I targeted the wrong litemod version, probably an older one than was released.  You definitely need to use the litemod, the base edit won't work.

I'll try compiling against `mod_WorldDownloader_8d05de448a5d76e4ec3acb325b8f641166fa158d_mc1.7.10.litemod` and see how that works.

**Comment by leopoldhub** [comment]
@Pokechu22 thanks ^^

**Comment by Pokechu22** [comment]
Here's a new version: [WDL-Keybinding-1.1.zip](https://github.com/Pokechu22/WorldDownloader/files/2228976/WDL-Keybinding-1.1.zip)

This targets `mod_WorldDownloader_8d05de448a5d76e4ec3acb325b8f641166fa158d_mc1.7.10.litemod`, and also adds <kbd>J</kbd> to open the settings GUI.

**Comment by leopoldhub** [comment]
@Pokechu22 YEAH!!! You are the best!!!! but... the mod is blocked with because the serveur say "you have an unexpected mod..." . . . do you know someone who can make a bypass for this mod?

**Comment by leopoldhub** [comment]
@Pokechu22 the admins are ok for downloading world but dont care of me :'( . . .

**Comment by leopoldhub** [comment]
if you can do it i want to give you something on paypal because your work is amazing!! (for the bypass i think something like this: https://www.youtube.com/watch?v=4yEAsYA_krM )

**Comment by Pokechu22** [comment]
I do not accept money, nor do I endorse any content in any video like that (the video is likely violating the mod's license).

Probably, the fix for this is to just make the thing I did as a forge mod into a litemod... but that will require me to set up a 1.7.10 liteloader workspace.  julialy mentioned the ant setup earlier; I'll see if I can get that figured out.

**Comment by uyjulian** [comment]
Tutorial on how to set up older Liteloader: https://www.youtube.com/watch?v=RMpvo-F4AFc

**Comment by Pokechu22** [comment]
As a litemod: [WDL-Keybinding-1.2.zip](https://github.com/Pokechu22/WorldDownloader/files/2229970/WDL-Keybinding-1.2.zip).  Setting that up reminds me once again how awful older toolchains are; I really don't know why people insist on still using 1.7.10 :/

**Comment by leopoldhub** [comment]
@pokechu22 first of all, im sorry, il don't know about the vidéo... and the for the money its for a donation and not for buying your work because i realy love your work and I want to help you for your dev ^^. Im going to test it after and thanks again  <3

**Comment by leopoldhub** [comment]
And, you ask " I really don't know why people insist on still using 1.7.10 :/" and I know why! ^^ its because the 1.7.10 is the Best and realy stable version for mods. It the version who have the most mods of all minecraft versions ...

**Comment by leopoldhub** [comment]
Its wonderfull!!!! my life is a success!!!! I L0VE You!!! i can dowload my build!!!!! I love your work!!!!

**Comment by leopoldhub** [comment]
hmmm... i cant open the map in singleplayer... its normal?

**Comment by Pokechu22** [comment]
I'm not entirely sure why that would be.  The map should be loadable in singleplayer, and there should also be a zipped copy in .minecraft/saves.

One idea: if you didn't stop downloading before disconnecting from the server, it might not have written a level.dat file; while that works normally it can't work with this keybinding variant (it normally attempts to stop downloading when the "disconnect" button is pressed, but that can't work with custom menus).

There might also be errors with registry contents not being saved; unfortunately, this cannot be fixed easily due to how old that version of the game is.  Let's hope that doesn't end up being an issue.

**Comment by leopoldhub** [comment]
ok, thanks for your help and your work! you are wonderfull!!

**Comment by Pokechu22** [comment]
Ah, and to clarify one thing: I don't accept money for anything related to the project, for personal reasons.  However, if you want to give money to someone, feel free to donate to the [Internet Archive Foundation](https://archive.org/donate/); they provide a rather important service.
