### ISSUE TITLE
1.13 please

### ISSUE THREAD

**Issue by Misio12320** [Pokechu22/WorldDownloader#88]
1.13

**Comment by Pokechu22** [comment]
It's in progress.

**Comment by uyjulian** [comment]
There's no limit on download size. What you see is what you download. Also, no ETA. "It's done when it's done".

**Comment by Misio12320** [comment]
Will it also download the chests with items hm?

**Comment by Pokechu22** [comment]
Yes, it will, in the same way it currently works (requiring opening the chests to save their contents).

**Comment by Misio12320** [comment]
Wtf @Pokechu22 you could say me about this Plugin before... Lol. Please make option download now without external site please I need this Plugin on Aternos but they dont add ''external site''

**Comment by Misio12320** [comment]
Ouh did the WD released? I only see source codes or idk. A suggestion if you can make WD plugin to upload world to some site from in game to a site and download this World... 3. Ouh you have time to make plugins for others for free hmm :s

**Comment by Pokechu22** [comment]
Oh, sorry, yeah; forgot about this report.  Yes; [v4.0.3.0](https://github.com/Pokechu22/WorldDownloader/releases/tag/v4.0.3.0) supports 1.13 and 1.13.1 (when installed on 1.13).  I'm not sure what else you're talking about, sorry; if you're talking about WDLC it's on github releases for its repo.

**Comment by Misio12320** [comment]
I think nvm about this plugin if released the Main downloader... How to install it? Hm
