### ISSUE TITLE
Server kick

### ISSUE THREAD

**Issue by DanLamp** [Pokechu22/WorldDownloader#89]
When i join a server i get kick and it say "please remove worlddownloader"

**Comment by Pokechu22** [comment]
Contact the server administrator and ask for more information/permission.  I cannot help you with this on github issues; it's the admin's responsibility.

If the admin refuses to help you, send me a PM on [the minecraft forums](https://www.minecraftforum.net/private-messages/send?recipient=Pokechu22).
