### ISSUE TITLE
HAVE NO IDEA HOW TO INSTALL

### ISSUE THREAD

**Issue by tonycool246** [Pokechu22/WorldDownloader#9]
I have no IDEA how to install it. Can you run me through with the steps? I tried doing it on my own, but doesnt seem to work

**Comment by Pokechu22** [comment]
Here's the steps from [the thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285484-world-downloader-mod): 

1. Close the launcher
2. Copy the %appdata%/.minecraft/versions/1.8 folder to %appdata%/.minecraft/versions/1.8_wdl
3. Go into folder 1.8_wdl.  Rename 1.8.jar to 1.8_wdl.jar
4. Rename 1.8.json to 1.8_wdl.json
5. Edit 1.8_wdl.json and replace text "1.8" with "1.8_wdl"
6. Open 1.8_wdl.jar using [7-zip](http://www.7-zip.org/); delete the META-INF folder and copy in the class files from the World Downloader zipfile.
7. Restart the launcher, "edit profile" (or make a new profile) and "use version" 1.8_wdl.

Alternatively, you can use @uyjulian's liteloader version, which is probably easier to set up: 

1. Download and run the [LiteLoader installer](http://jenkins.liteloader.com/job/LiteLoaderInstaller/).
2. Launch minecraft once with the new "LiteLoader" profile; this will create the needed folders.
3. Go to %appdata%/.minecraft, and put the [WDL litemod file](https://bintray.com/artifact/download/uyjulian/MinecraftMods/mod_WorldDownloader_a09739ce7a82d02268eedb5c03e3f444813b18ff_mc1.8.litemod) into the mods folder.

**Comment by tonycool246** [comment]
OMG thanks dude.. much love <3
