### ISSUE TITLE
How to Install on 1.13.1

### ISSUE THREAD

**Issue by Misio12320** [Pokechu22/WorldDownloader#91]
As in title how to install..

**Comment by Pokechu22** [comment]
Due to the current process, you actually install the 1.13.1 version onto 1.13 and then connect from 1.13 to a 1.13.1 server (which normally does not work, but I implemented).  Apart from that the installation process is the same as normal, but if you need help for installing it in general, let me know.

**Comment by Misio12320** [comment]
Can I get a tutorial or some like this I founded only .zip and nothing more...

**Comment by Pokechu22** [comment]
There are some installation instructions [on the forum post](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2520465-1-12-2-1-11-2-1-10-2-1-8-9-world-downloader-mod#Installation); you will want to follow the base edit instructions.

**Comment by Misio12320** [comment]
Omg. Step by step... I download  .litemod whats next   ..... Omg

**Comment by V-DeVito** [comment]
First, gotta chill out bro. 

Don't download litemod, download this[https://github.com/Pokechu22/WorldDownloader/releases/download/v4.0.3.0/mod-worlddownloader-baseedit-4.0.3.0-mc1.13.1-from-1.13.zip](url)

Download https://multimc.org/

Run MultiMC

1. Select New Instance
2. Make sure you select 1.13
3. Once it's created, select edit instance
4. Select "add to minecraft.jar" from the list on the right side.
5. Select the downloaded mod, it should end in .zip
7. Once the mod is added, launch the instance.

Enjoy World Downloader for 1.13.1

**Comment by Pokechu22** [comment]
^ That's exactly what you need to do.  Thanks for writing that up; I've been a bit busy today.

**Comment by Misio12320** [comment]
Rly I need premium minecraft? FFFS another way? any crack or some instant done

**Comment by Pokechu22** [comment]
Yes, you need to have purchased the game to use this mod.  If you haven't purchased it, I will not help you, and you cannot use the mod.  Just buy the game, it's not that expensive.  This issue is closed.

**Comment by Misio12320** [comment]
Kk. What if I buy the game and couldnt work multimc or the WorldDownloader on my world which have 1-3gb?

**Comment by Pokechu22** [comment]
If that issue comes up, let me know and I can try to diagnose it.  Worst case, though, you'll have bought the game which you're already playing - not the end of the world and in fact something you probably should have already done.

**Comment by Misio12320** [comment]
Ouh. Have you maybe discord or some like this?

**Comment by Pokechu22** [comment]
Unfortunately, I do not.

**Comment by V-DeVito** [comment]
I do. Write down your username and I'll message you.

**Comment by Misio12320** [comment]
Ouh wot... I did not asked here for a Dev to get plugin for free or wtf whooat

**Comment by V-DeVito** [comment]
Hey man, we're trying to help. We're not getting anything for free. If you want to contact via discord, leave your username here.

**Comment by Misio12320** [comment]
Okay okay... I was thinking if you was asking a discord contact about plugin create i was thinking about Pokechu22 if he could do this but I did not wrote that lol.. Im rly lost for today sorry...

**Comment by Misio12320** [comment]
I understand the help need buy Mc premium ok but not now... Also I ask later how to make this on 1.13.1 i half understand of this but not 3v3rything....

**Comment by V-DeVito** [comment]
Once you get the game, we’ll explain how to do it on 1.13.1.   It’s kind of hard to explain when you can’t follow along.

**Comment by Misio12320** [comment]
Unstable 1.13.1 WDL bridge with caution..

**Comment by Misio12320** [comment]
Working Omg lool. And Wheres % download... Edit. When will the chests are fixed? How to make it to download the world with more than 10 mobs, villagers, sheeps etc. EDIT x4 rip... Kk So... The world downloaded in 3 MB :S lol and... Idk EDIT x5... It looks that https://gyazo.com/6a4624899600daeb965f7b9106ceb2eb why the built isnt all... But the most expensive is for me the chests

**Comment by V-DeVito** [comment]
Separate issues. This issue is closed.
