### ISSUE TITLE
Message hover text formatted incorrect

### ISSUE THREAD

**Issue by Selebrator** [Pokechu22/WorldDownloader#95]
The hovering message is not formatted optimally. 
I'm assuming `\n` is actually supposed to be a line break, the text is not supposed to overshoot the window and the text shadow is supposed to be under the corresponding letters.
![2018-09-20_19 34 29](https://user-images.githubusercontent.com/17477114/45838280-a54a3e00-bd11-11e8-8b8f-9f34b22c5f6f.png)

liteloader: `1.12.2-SNAPSHOT-r4CC2BB0-b4-4` (latest)
litemodwdl: `4.0.3.0-1.12.2` (1 behind latest)

**Comment by Pokechu22** [comment]
Huh, yeah, that looks messed up.  I don't think that's specific to the update notification; every message from the mod has a hover event on the `WorldDL` text.

I did make some changes in 4.0.3.0 with regards to newlines, so probably the escaped newlines are from that.  The bold, though, makes no sense to me; I have no idea why "mod" is in bold (if I recall correctly only the "You can disable this message" part is supposed to be bold) or why it's wrapped like that.  Weird...

**Comment by Pokechu22** [comment]
Looks like I actually broke it more in 4.0.3.1; the text has a component in the middle of it:


![2018-09-20_14 22 05](https://user-images.githubusercontent.com/8334194/45847707-c34b7a80-bce0-11e8-84b8-02d92b3fced1.png)

In 1.13, the newline does actually work correctly, though (1.12.2 is still broken as seen above):

![2018-09-20_14 16 09](https://user-images.githubusercontent.com/8334194/45847702-bcbd0300-bce0-11e8-8d3a-8bd99ee960df.png)

**Comment by Pokechu22** [comment]
This should be fixed in the next build (not yet released).
