### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by Misio12320** [Pokechu22/WorldDownloader#98]
Is it possible to download the world to the border? Like i had 10k blocks to the border and i dont want fly 100k blocks a feature some? And if you can make Pokechu22 to download world with filled chunks?

**Comment by Pokechu22** [comment]
I'm not entirely sure what you're saying.  If you mean downloading an area beyond what the client can see, unfortunately that's not possible; you do have to load all of that area to save it and that's not something that's possible to change because of how the game works.

**Comment by Misio12320** [comment]
Ouh.... So the fill world i need to do on another hosting right? Well... On aternos shit possible no more than 1gb

**Comment by Misio12320** [comment]
@Pokechu22 can I add huzuni/wurst or other mods into WorldDownloader 1.12.2? He said if ''they cannot give seed of world'' The new chunks isnt generating by huzuni FreeCam any cheat to get the chunks without running like free cam or fly somethis?

**Comment by Pokechu22** [comment]
No.  I do not, cannot, shall not, and will never support such mods.

**Comment by Misio12320** [comment]
I Just asked if I can add WD and huzuni into 1 launcher lol
